### ISSUE TITLE
Add Microsoft OneDrive support to remote storage

### ISSUE THREAD

**Issue by watchfulli** [watchfulli/XCloner-Wordpress#102]

**Comment by ovidiul** [comment]
OneDrive support as been added to the remote storages options, we also need to build up a tutorial page for it as it can be tricky to setup the Azure App

<img width="995" alt="Screenshot 2020-07-01 at 08 23 16" src="https://user-images.githubusercontent.com/537751/86206045-2172e600-bb74-11ea-8411-0d7e573b5391.png">
