### ISSUE TITLE
Test Basic Features

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#103]
Hi @jimiero  we need help with testing this milestone release as it includes some overall code changes, here is a summary of what we would need to check:

- [x] Basic Settings can be saved
- [x] Remote Storages settings can be saved and can be validated against valid credentials (spot-test with existing cloud credentials from LastPass)
- [x] Generate Backup - full backup with default settings
- [x] Generate Backup - partial backup with some tables excluded
- [x] Generate Backup - partial backup with some files excludes
- [x] Generate Backup - partial backup with additional databases included
- [x] Generate Backup - full backup with encryption enabled
- [x] Generate Backup - full backup transferred to Dropbox
- [x] Generate Backup - full backup transferred to Dropbox and deleted from local
- [x] Manage Local Backups - Make sure backups are listed.
- [x] Manage Local Backups - Make sure backups can be deleted
- [x] Manage Local Backups - Make sure backups can be uploaded to DropBox
- [x] Manage Local Backups - Make sure backups can be downloaded. 
- [x] Manage Local Backups - Make sure backup contents can be listed.
- [x] Manage Local Backups - Make sure an encrypted backup can be unencrypted.
- [x] Manage Dropbox Backups - Make sure backups are listed.
- [x] Manage Dropbox Backups - Make sure backups can be deleted
- [x] Manage Dropbox Backups - Make sure backups can be uploaded to DropBox
- [x] Manage Dropbox Backups - Make sure backups can be downloaded. 
- [x] Manage Dropbox Backups - Make sure backup contents can be listed.
- [x] Manage Dropbox Backups - Make sure an encrypted backup can be unencrypted.
- [x] Create a Scheduled Profile
- [x] Check the correct recurrence of a scheduled Profile based on the Wordpress cronjob execution
- [x] Trigger any backup profile from the XCloner CLI 
- [x] Restore full backup locally
- [x] Restore full backup to a remote location
- [x] Enable/Disable logs - check if enabling/disabling logs in XCloner works

**Comment by vdrover** [comment]
Looks liek we're ready to go.
