### ISSUE TITLE
Selecting checkbox for a backup in "Manage backups" selects wrong backup

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#104]
When you go to "Manage backups" section and select a backup checkbox, it selects the backup under the one you selected.

It should select the correct backup

![Screen Shot 2020-06-12 at 11 57 19 AM](https://user-images.githubusercontent.com/3626762/84485173-6d80e800-aca4-11ea-9b4c-3d8c66dfedd1.png)

**Comment by ovidiul** [comment]
Fix posted in the latest milestone 4.2.1
