### ISSUE TITLE
Load webdav vendor lib only if webdav is activated

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#107]

**Comment by ovidiul** [comment]
It seems the only solution i have here is to move the webdav remote storage option to it's separate plugin as with google drive, the sabre lib currently requires the use of php7.1, while recommended wordpress version is 7.3 , so i think we should be good with this.

Let me know if we need to look more into this.

**Comment by vdrover** [comment]
That's a bummer, but I get it. Will we need a new repo? How will the upgrade process work?

**Comment by ovidiul** [comment]
Yes, new repo, new wordpress plugin same as the google drive one, upgrade will be done at the plugin level specifically
