### ISSUE TITLE
[cleanup settings] global cleanup settings are overriding the remote storage cleanup

### ISSUE THREAD

**Issue by raramuridesign** [watchfulli/XCloner-Wordpress#109]
**Settings for remote storage**

When setting the remote storage example S3 to cleanup data every 120 days

**Global Settings - Cleanup**

Settings set to 1 day 

![image](https://user-images.githubusercontent.com/902376/86114124-6b06f680-baca-11ea-9627-a9c8b6e79a01.png)

If you process a backup either from website or remotely from Watchful, the backup is transferred to S3 and all backups are removed and only the backup which was processed remains.

So, it looks like global settings are overriding the remote storage cleanup settings.
Should global settings not apply to LOCAL storage ONLY?

**Comment by ovidiul** [comment]
I've found indeed an issue there, please check the code in milestone4.2.9 branch and let me know if you have anymore issues.

**Comment by raramuridesign** [comment]
@jimiero would you mind installing on watchful blog and seeing if this is there. I will check S3 when this has been tested.

**Comment by jimiero** [comment]
@ovidiul any idea how we can test this on a prod website, as the milestone branch has different folder than the official release, and will cause plugin installing two times

**Comment by ovidiul** [comment]
Simply remove the old plugin, install the new one and rename the plugin folder xcloner-backup-and-restore if you need compatibility with watchfulli plugin.

**Comment by jimiero** [comment]
@ovidiul we tested with the new version from milestone 4.3.0 and now the options are are respected, just that we see the "Cleanup options" tab missing from XCloner settings, see attached image

![cleanul-tab-missing](https://user-images.githubusercontent.com/3626762/86438691-bf4ee800-bd0f-11ea-9019-46524482f3eb.png)

**Comment by raramuridesign** [comment]
@ovidiul Just so you know
we have this documented on XCLONER docs
https://docs.xcloner.com/#/wordpress/optimize-your-backups/cleanup-options

So if something like this changes, we do need to know - just a heads up... thanks.

@vdrover

**Comment by ovidiul** [comment]
Hi guys, the cleanup options have been moved to Storage locations->Local Storage . Let me know if you think they make more sense to put them back in the settings area.

**Comment by raramuridesign** [comment]
@ovidiul I think this does make sense, but this will need to be checked by @vdrover if this is good.
We will need to adjust docs accordingly once this has been done.

Is a new version expected sometime soon?

**Comment by ovidiul** [comment]
1-2 weeks for the new version as it requires more testing.

**Comment by ovidiul** [comment]
@raramuridesign @vdrover i think we can mark this as closed. please re-open it if you have notice further issues
