### ISSUE TITLE
Backup Site Url: http instead of https

### ISSUE THREAD

**Issue by mdes** [watchfulli/XCloner-Wordpress#110]
Hi,

The email sent after the backup shows **Backup Site Url: http://…**, but my site is **https://…**
Site and Wordpress Urls are correctly set to  **https://…**.

Do yo have an idea where this issue is coming?

Regards,
Michel.

**Comment by ovidiul** [comment]
Hi Michel, can you check what is the value of your "Site Address (URL)" in Settings->General? XCloner uses that option when publishing the email

**Comment by mdes** [comment]
Hi Ovidiul,
As I wrote, site and Wordpress Urls are correctly set to https://… in the general settings.
