### ISSUE TITLE
[xcloner backend] Weird POPUP showing on various pages

### ISSUE THREAD

**Issue by raramuridesign** [watchfulli/XCloner-Wordpress#112]
**ISSUE**
This affects the latest releases
XCloner-Wordpress-milestone4.3.0.zip > tested for #109 
and
XCloner-Wordpress-milestone4.2.9.zip

This issue has been noted after an issue with issue #109 - (this seems to be working now) and is being tested on the LIVE BLOG from Watchful as we needed to get the backups of the site working with XCLONER - hence the isues.

**@ovidiul if you need access to see this, please ping me on SLACK**

**URLS AFFECTED**
/wp-admin/admin.php?page=xcloner_manage_backups_page
/wp-admin/admin.php?page=xcloner_scheduled_backups_page
/wp-admin/admin.php?page=xcloner_generate_backups_page
/blog/wp-admin/admin.php?page=xcloner_restore_page

**SCREENSHOTS OF THE PAGES ABOVE**
In the screenshots, you can see the popup, this does not go away and remains on the screen all the time.
Note, we have not clicked anything, it just stays where it is.
Does not seem to be any console errors either.

![image](https://user-images.githubusercontent.com/902376/86438872-a5a9a280-bd07-11ea-921f-f964a3a5826b.png)
![image](https://user-images.githubusercontent.com/902376/86438882-ab9f8380-bd07-11ea-8c51-98ca390479dd.png)
![image](https://user-images.githubusercontent.com/902376/86438893-b1956480-bd07-11ea-95b3-5cfece619712.png)
![image](https://user-images.githubusercontent.com/902376/86438903-b6f2af00-bd07-11ea-95a0-ceb874d9d18a.png)

**BROWSER TESTED ON**
- chrome
- Brave browser
- firefox

Any more info needed, let me know
Matthew

**Comment by vdrover** [comment]
@ovidiul can u look into this please?

**Comment by ovidiul** [comment]
Ho @vdrover @raramuridesign this is fixed already in latest release, let me know if you have further issues.

**Comment by vdrover** [comment]
We're still seeing it on the Watchful blog.

**Comment by ovidiul** [comment]
Seems the original issue was caused by a conflict with the embedpress plugin, i've found a solution and posted the fix in the milestone4.2.13 branch, also updated the code on watchful blog

Let me know if you have anymore issues.
