### ISSUE TITLE
Improve Google Drive integration

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#113]
Check and see if we can improve our Google Drive integration flow, currently the integration is kinda complex to get it done, and some none experienced users may not be able to achieve it.

Check and see if we can have it working with one click connection to Google and ask for permissions.

**Comment by ovidiul** [comment]
GoogleDrive app has been created and we can now authenticate users without having them to provide Client ID and Secret.

**Comment by Ars92** [comment]
Next step could be to automatically add the secret code into storage settings instead of asking the user to paste it into the field.
