### ISSUE TITLE
Google Drive upload issue

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#114]
Seems there's a bug when you try to upload a backup on Google Drive.

`php_system.ERROR: E_ERROR: array ( ‘type’ => 1, ‘message’ => ‘Uncaught Google_Service_Exception: Global HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps. in wp-content/plugins/xcloner-google-drive/vendor/google/apiclient/src/Google/Http/REST.php:118 Stack trace: #0 /wp-content/plugins/xcloner-google-drive/vendor/google/apiclient/src/Google/Http/REST.php(94): Google_Http_REST::decodeHttpResponse(Object(GuzzleHttp\\Psr7\\Response), Object(GuzzleHttp\\Psr7\\Request), NULL) #1 /wp-content/plugins/xcloner-google-drive/vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Http_REST::doExecute(Object(GuzzleHttp\\Client), Object(GuzzleHttp\\Psr7\\Request), NULL) #2 /wp-content/plugins/xcloner-google-drive/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Task_Runner->run() #3 /wp-content/plugins/xcloner-google-driv’, ‘file’ => ‘/wp-content/plugins/xcloner-google-drive/vendor/google/apiclient/src/Google/Http/REST.php’, ‘line’ => 118, ) [] []`

**Comment by ovidiul** [comment]
Hi @jimiero i have a fix available for this bug, can you check if it works ok by updating the XCloner Google Drive plugin from https://github.com/watchfulli/XCloner-Google-Drive/archive/dev.zip

I will make a pull request on master once confirmed so we can prepare the release in the wordpress repo.

**Comment by jimiero** [comment]
One customer reported that issue gets fixed with this version.

**Comment by ovidiul** [comment]
Perfect, i've merged the code into master branch, we just have to release it on wordpress repo now.
