### ISSUE TITLE
Migrating website to different webhosting where paths changes

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#120]
When you migrate a website to a different host that has different file/folders path, causes an issue where XCloner plugin can't be activated in site backend

Maybe find a way to allow changing the paths in XCLoner configuration even with XCloner disabled

**Comment by ovidiul** [comment]
Hi @jimiero  fix has been posted in the milestone branch.

Let me know if you have notice further issues.
