### ISSUE TITLE
Replace `upload to local storage` icon and lang string

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#121]
On the 'Manage Backups' screen we have an upload icon to transfer remote backups to the local server. I think it's a bit confusing: for some folks at least, this might be considered a download. 

I propose 2 changes:

1. Change the icon from `upload` to `transfer`. This icon is what I had in mind: https://fontawesome.com/icons/exchange-alt?style=solid

2. Modify the language string from `Push backup to local storage` to `Transfer a copy of the remote backup to local storage.`

**Comment by ovidiul** [comment]
Hi @vdrover 

@1 please check the proposed icon from this list https://materializecss.com/icons.html , will this work?

<img width="1220" alt="Screenshot 2020-08-17 at 20 49 55" src="https://user-images.githubusercontent.com/537751/90427802-b6518480-e0cb-11ea-8016-88b6c67c1d32.png">


@2 done

**Comment by vdrover** [comment]
Perfect.

**Comment by vdrover** [comment]
Tou'll add this to the screen when remote storage is also selected?

**Comment by ovidiul** [comment]
Sure, done now

<img width="798" alt="Screenshot 2020-08-19 at 13 08 31" src="https://user-images.githubusercontent.com/537751/90621942-1a379280-e21d-11ea-9a38-afa0a6010a6a.png">

**Comment by vdrover** [comment]
Not seeing it with 4.1.13.
<img width="1437" alt="Image 2020-08-19 at 12 02 33 PM" src="https://user-images.githubusercontent.com/3143313/90667126-fa4fa100-e213-11ea-9852-32a64b312dc2.png">

**Comment by ovidiul** [comment]
Weird, can you try and reinstall the package from here https://github.com/watchfulli/XCloner-Wordpress/archive/milestone4.2.13.zip

**Comment by vdrover** [comment]
I installed from the WP repo.
