### ISSUE TITLE
Add a `direct download` icon in the remote storage area of `Manage Backups` 

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#122]
To download a backup to your PC, you must be viewing the local storage area. 

When you switch to S3 (for example) there is no download link. We should have a direct download here to let folks skip the 'transfer to local' step if they desire.

**Comment by ovidiul** [comment]
Download button enabled now for remote storage locations

<img width="1039" alt="Screenshot 2020-08-19 at 13 21 06" src="https://user-images.githubusercontent.com/537751/90623560-50761180-e21f-11ea-8c3b-52a1dd0c4eb2.png">

**Comment by vdrover** [comment]
sweet!
