### ISSUE TITLE
Soften `File does not exist on local storage` alert.

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#123]
In the remote area of `Manage Backups`, a red alert is shown when the backup archive does not exist on local storage. Red indicates an error. However, this may be the desired situation if local cleanups are enabled. 

I propose the following:

1. Change icon from red to yellow.

2. Change language string for the tooltip from `File does not exist on local storage.` to `This backup archive does not exist on your local server. If you wish to retain local copies of your backup archives as well as remote copies, please disable local clean-up in the main XCloner settings and/or your scheduled backup profile settings.`.

**Comment by ovidiul** [comment]
Hi @vdrover color and text changes have been posted to attached milestone branch.

<img width="659" alt="Screenshot 2020-08-19 at 12 24 48" src="https://user-images.githubusercontent.com/537751/90617311-35070880-e217-11ea-8270-38499666f9f0.png">

**Comment by vdrover** [comment]
great!
