### ISSUE TITLE
How to deal with `tested up to WP Vversion x.y.z` changes

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#124]
@ovidiul Can we add something to our release workflow to update this value on every release? Perhaps something that gets baked into the pre-release testing?

![image](https://user-images.githubusercontent.com/3143313/90263228-fa672f80-de14-11ea-852d-272a201a4b4d.png)

In fact we need a new release for WP 5.5. 

More info here: https://treeflame.slack.com/archives/C130833K4/p1597165196230900

**Comment by ovidiul** [comment]
Hi @vdrover  this value is hardcoded into the README.txt annotations, we could only do this if we are to automatically generate that file using some custom parameters. Right now, the tested up version change is only needed when WP does a major change from 5.4 to 5.5 for instance, and not for minor versions line 5.4.1

On each major WP release, we need to test the plugin and having it manually update the README.txt once is not a major task in my opinion.

Let me know how to want to handle this further.
