### ISSUE TITLE
Remove modal following remote upload

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#125]
Are we able to remove this modal entirely and have the status message just show up along with the other messages?

<img width="1171" alt="Image 2020-08-17 at 1 30 38 PM" src="https://user-images.githubusercontent.com/3143313/90431047-0b6ea580-e08e-11ea-94e5-adf75b926df0.png">

**Comment by ovidiul** [comment]
Hi @vdrover option is now added in the current milestone

<img width="1160" alt="Screenshot 2020-08-19 at 15 04 53" src="https://user-images.githubusercontent.com/537751/90632686-7c988f00-e22d-11ea-85a2-22ca49aa4147.png">

**Comment by vdrover** [comment]
fantastic.
