### ISSUE TITLE
Need editable region option for AWS-compatible service

### ISSUE THREAD

**Issue by VampiRUS** [watchfulli/XCloner-Wordpress#128]
If i've set custom endpoint also i need to set custom region value. For example in yandex.cloud region must be set to 'ru-central1'

**Comment by vdrover** [comment]
@jimiero This is not an issue anyone can help with. No info, no content. Closing.

**Comment by ovidiul** [comment]
Just an update, option will be added in the next release, another task addressing this is opened here https://github.com/watchfulli/XCloner-Wordpress/issues/132
