### ISSUE TITLE
numeric off_t value expected

### ISSUE THREAD

**Issue by edisoncosta** [watchfulli/XCloner-Wordpress#13]
Hi.

I'm using xcloner to generate backup and created a script to unpack the files, as a restore function.

The problem that often occurs is:

tar: Archive contains '\ 006 \ 253 \ 006 \ 236 \ 250 \ 026u \ 032МQ \ 365' where numeric off_t value expected

varying the content, of course.

I am using tar command below:

tar -xvf name_file.tar

I tried other variations, but without success.

Thank you.

**Comment by ovidiul** [comment]
Do you get this error for all backups created with XCloner or only with this specific backup? Could you share the tar archive with me to check as well?

**Comment by edisoncosta** [comment]
They are not all, but they happen very often.
I sent the link with backup access to info@thinkovi.com.

**Comment by vdrover** [comment]
Is this still occurring? Please re-open as needed.
