### ISSUE TITLE
Add option to completely remove XCloner options for a fresh install

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#131]
We should add a button in the XCloner Setttings that will restore XCloner to it's default state, meaning we should delete all XCloner saved options and re-run the activator method once again.

**Comment by vdrover** [comment]
Agree.

**Comment by ovidiul** [comment]
Hi @vdrover option added in the 4.2.13 branch

<img width="760" alt="Screenshot 2020-08-24 at 14 42 27" src="https://user-images.githubusercontent.com/537751/91041781-471ee780-e619-11ea-81f1-56ecde80fae9.png">

Let me know if you need further changes.
