### ISSUE TITLE
Add CLI support for standalone backup encryption/decryption

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#136]
While XCloner supports encryption and decryption of backup archives based on a set key using it's visual interface, it would be useful to add this kind of support at CLI level.

It should support both standalone versions as well as WP-CLI plugin integration.

**Comment by vdrover** [comment]
Fantastic. Please keep me informed of all CLI changes so we can keep docs updated.

The XCLoner CLI needs a `-help` argument like the WP CLI.

**Comment by ovidiul** [comment]
Hi @vdrover  we already have a -h option for the CLI commands to display us the list of available options

<img width="574" alt="Screenshot 2020-09-02 at 11 04 57" src="https://user-images.githubusercontent.com/537751/91965873-c39c7f00-ed19-11ea-9462-90e0e552cb7b.png">

I have now added also the option to encrypt/decrypt backups using a custom or default encryption key

Let me know if find an issues.

**Comment by ovidiul** [comment]
Just a quick note, the https://docs.xcloner.com/#/wordpress/advanced-backups/xcloner-cli and https://docs.xcloner.com/#/wordpress/advanced-backups/wp-cli will need to be updated with the new commands:

### WP-CLI:
wp xcloner_generate_backup --encrypt [backup_name] --key [encryption key]
wp xcloner_generate_backup --decrypt [backup_name] --key [decryption key]

### XCLONER CLI

php ~/public_html/wp-content/plugins/xcloner-backup-and-restore/xcloner.php -e [backup name] -k [encryption key]
php ~/public_html/wp-content/plugins/xcloner-backup-and-restore/xcloner.php -d [backup name] -k [decryption key]
