### ISSUE TITLE
Add CLI support for backup archive files listing

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#138]
From a CLI perspective, it would be very useful to add a command to list the backup archive content, so I propose we add a command in the next release to support both WP CLI and XCloner CLI.

**Comment by ovidiul** [comment]
Option added for --list | -l for listing backup contents at CLI/WP-CLI side

<img width="1357" alt="Screenshot 2020-09-16 at 15 34 35" src="https://user-images.githubusercontent.com/537751/93337695-2588d880-f832-11ea-8e03-3aa3fd7c6184.png">

**Comment by Ars92** [comment]
@jimiero 
can you please test if this can be considered as done?
