### ISSUE TITLE
Replace Backblaze lib with S3 compatible one

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#139]
Backblaze remote storage location announced they have support for S3 like api calls https://www.backblaze.com/b2/docs/s3_compatible_api.html , XCloner should replace the existing library as it's not maintained anymore and use the AWS S3 lib instead with the necessary API config changes.

**Comment by Ars92** [comment]
The libraries and the API used by the libraries are still maintained.
On Backblaze docs they specified that:
>Backblaze does not have any plans to stop supporting old versions. If we ever do make such plans, we will announce them at least a year in advance, to give you plenty of time to update your code. 

I'm closing this for now.
