### ISSUE TITLE
Implement automated frontend testing

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#140]
@vdrover this task is a more long haul task, i am just putting it here for reference.

There are multiple JS libraries that could be used for frontend testing, and so it would help us automate the Pre-release task we have currently occurring on each release, one of these libs being https://www.cypress.io/ .

At some point, we should start implementing this into our frontend testing procedures, so for instance @jimiero could automate all his work at some point.

**Comment by vdrover** [comment]
that would rock.
