### ISSUE TITLE
Design Changes Proposal

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#147]
![xcloner-suggestion - buttons](https://user-images.githubusercontent.com/537751/92471857-4f624f80-f1e1-11ea-8f80-f2e63b7bad05.png)

@raramuridesign  suggets a design change as above, with mentions that the Start Backup button should be placed to the top right

@vdrover do you have any other input on this and if we can include it in the next release?

**Comment by vdrover** [comment]
I like moving the buttons above the content and below the tabs. Also justify them left. 

As for the menu, this is not really part of the WP UI. I'm open to considering this but need some concept art from @raramuridesign  .

**Comment by ovidiul** [comment]
Hi @raramuridesign @vdrover I am proposing the below design for menus and design button

<img width="711" alt="Screenshot 2020-09-16 at 14 23 41" src="https://user-images.githubusercontent.com/537751/93331103-74317500-f828-11ea-861c-946592ac29bf.png">
<img width="603" alt="Screenshot 2020-09-16 at 14 23 57" src="https://user-images.githubusercontent.com/537751/93331117-785d9280-f828-11ea-87e6-6a595462cff4.png">
<img width="1030" alt="Screenshot 2020-09-16 at 14 24 01" src="https://user-images.githubusercontent.com/537751/93331119-78f62900-f828-11ea-9fa4-e46f273b1fbb.png">
<img width="1145" alt="Screenshot 2020-09-16 at 14 25 56" src="https://user-images.githubusercontent.com/537751/93331149-81e6fa80-f828-11ea-984f-c6fbd18b376e.png">

Let me know if you need further changes, you can test this code already in the 4.2.16 branch

**Comment by raramuridesign** [comment]
@ovidiul This looks really great. One thing I do think which is missing, not sure if its been missed. but where is the branding
ie a logo? top left perhaps ie to the right of the new button you added.
@vdrover not sure if this has been removed or considered as an addition?

but the buttons and menu look perfect.

**Comment by vdrover** [comment]
This feels a little clunky to my, though I like the features. Can u right justify all the new elements and show a full screenshot?

**Comment by ovidiul** [comment]
The page title with the menu has to stay in the left, but i've moved the other sub-elements to the right, let me know if this helps

<img width="1242" alt="Screenshot 2020-09-16 at 16 46 38" src="https://user-images.githubusercontent.com/537751/93346080-3fc7b400-f83c-11ea-8d80-c91da58e8924.png">

**Comment by raramuridesign** [comment]
@ovidiul looks good for me - what about the logo? top right any consensus on this?

**Comment by vdrover** [comment]
looks better on the right.

**Comment by ovidiul** [comment]
@raramuridesign  here is the logo, will this work?

<img width="1299" alt="Screenshot 2020-09-16 at 17 16 54" src="https://user-images.githubusercontent.com/537751/93349696-7bfd1380-f840-11ea-86e2-018c6d7675c9.png">

**Comment by vdrover** [comment]
Let's make it 25% smaller and use the color one.

**Comment by ovidiul** [comment]
<img width="1316" alt="Screenshot 2020-09-16 at 17 52 53" src="https://user-images.githubusercontent.com/537751/93354233-735b0c00-f845-11ea-987a-b23e127f552c.png">

let me know if you need further changes

**Comment by vdrover** [comment]
<img width="824" alt="Image 2020-09-16 at 10 06 18 AM" src="https://user-images.githubusercontent.com/3143313/93355997-49352a00-f804-11ea-9831-a14e5b7b7965.png">

The right edge of the logo should align with the right edge of the rest of the UI I think.

**Comment by raramuridesign** [comment]
![screenshot-xcloner-logo](https://user-images.githubusercontent.com/902376/93356710-cf229680-f83f-11ea-8db7-5fe84d9eecbe.png)

Here is the placement of the center of the button based on vics suggestions

**Comment by ovidiul** [comment]
Ok, please check this option attached

<img width="1138" alt="Screenshot 2020-09-16 at 22 52 22" src="https://user-images.githubusercontent.com/537751/93385697-46bbea00-f86f-11ea-9cb1-42d0df58413b.png">

**Comment by raramuridesign** [comment]
@ovidiul looks good ;-)
