### ISSUE TITLE
OneDrive documentation is outdated

### ISSUE THREAD

**Issue by fooforge** [watchfulli/XCloner-Wordpress#156]
Hi folks,

Not an issue with the code here itself, but the documentation for setting up OneDrive storage at https://docs.xcloner.com/#/wordpress/configure-remote-storage/onedrive-storage is fairly outdated. The registration process has changed so that you need to define an account type now. I wasn't able to get the integration to work unless I've selected _"	Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"_.

If the documentation is Open Source (didn't find a corresponding repository), I'm happy to take a stab at updating the docs. Otherwise, here's your notification to add this to your backlog. ;-) Cheers!

**Comment by jimiero** [comment]
Hello @fooforge thanks for your feedback, we've applied those changes, please check link below:

https://docs.xcloner.com/#/wordpress/configure-remote-storage/onedrive-storage

**Comment by fooforge** [comment]
> Hello @fooforge thanks for your feedback, we've applied those changes, please check link below:
> 
> https://docs.xcloner.com/#/wordpress/configure-remote-storage/onedrive-storage

Looks great. Thanks! ✨
