### ISSUE TITLE
XCloner detected as possible PHP Injection threat by watchful

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#161]
<img width="1311" alt="Image 2020-11-20 at 10 51 33 AM" src="https://user-images.githubusercontent.com/3143313/99827015-b88a0b80-2b1e-11eb-97cb-0adfdac3cda6.png">

The second column shows the signature match.

Anything to be done?

**Comment by martin-braun** [comment]
These are clearly issues of the used vendor scripts [sabre/dav](https://github.com/sabre-io/dav) and [League\Flysystem](https://github.com/thephpleague/flysystem). You could create issues over there and also [contact the author of League\Flysystem in regards of a potential security issue](https://github.com/thephpleague/flysystem#security). Those libraries are probably already safe and watchful can see the potential without seeing the prior validation that makes sure an injection cannot happen. The only true alternative for this to find other methods to use DAV/S3/etc., something that I don't see coming as well.

You probably have to just ignore those warnings. Security standards look high to me on the given vendor scripts.
