### ISSUE TITLE
phpMyAdmin Import Errors - Duplicate entry for key PRIMARY

### ISSUE THREAD

**Issue by skibulk** [watchfulli/XCloner-Wordpress#17]
Hi if I take the SQL backups generated by xcloner and try to import them into a database using phpMyAdmin sometimes I get errors similar to this:

_#1062 - Duplicate entry '267032' for key 'PRIMARY'_

The same error occured in at least my last two database backups, 12/20 and 12/21
I'm using the latest version of WP and XCloner, and phpMyAdmin v4.7.3.

**Comment by ovidiul** [comment]
You might need to check your mysql backup file, do you have duplicate entries with key "267032" for the same table? You might need to remove one of them then try again

**Comment by skibulk** [comment]
I know how to hack it. What I'm saying is there's a problem with the sql backup script to cause this?

**Comment by ovidiul** [comment]
To debug the issue, first you would need to check if there is a duplicate record in the export table for that key,  does a second backup create the issue at the same record id?

**Comment by skibulk** [comment]
In the backup from 12/21, the following lines cause the error. These are wordfence entries.

```
INSERT INTO `wp_wfHits` VALUES ('267032', '0.000000', '1513777846.557384', '\0\0\0\0\0\0\0\0\0\0��70', '0', '200', '0', '0', '0', 'http://www.example.com/wp-login.php', '', 'Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.0', '', '', '');
INSERT INTO `wp_wfHits` VALUES ('267032', '0.000000', '1513777846.557384', '\0\0\0\0\0\0\0\0\0\0��70', '0', '200', '0', '0', '0', 'http://www.example.com/wp-login.php', '', 'Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.0', '', '', '');
```

In the backup from 12/20, the following lines cause the error. These are also wordfence entries.

```
INSERT INTO `wp_wfHits` VALUES ('264330', '0.000000', '1513720143.972050', '\0\0\0\0\0\0\0\0\0\0��)ܧ, '0', '200', '0', '0', '0', 'http://example.com/wp-login.php', '', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1', '', '', '');
INSERT INTO `wp_wfHits` VALUES ('264330', '0.000000', '1513720143.972050', '\0\0\0\0\0\0\0\0\0\0��)ܧ, '0', '200', '0', '0', '0', 'http://example.com/wp-login.php', '', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1', '', '', '');
```

**Comment by ovidiul** [comment]
Have found any other occurrences of duplicate entries or is this the only one? I will look more into the issue once i find some time. If you can, feel free to send me a copy the backup archive to look more into the issue, you can contact me here http://www.thinkovi.com/contact/ ,thanks.

**Comment by vdrover** [comment]
Is this still an issue? Please re-open as needed.
