### ISSUE TITLE
Scheduled backups too small

### ISSUE THREAD

**Issue by martin-braun** [watchfulli/XCloner-Wordpress#179]
Running a manual backup with XCloner in my WP instance will result in a 2GB file, but configuring XCloner to automatically do the backup will only end up with a 200MB file. The host allows to override php.ini variables by placing a php.ini in the directory of work. I placed a php.ini into the root and wp-admin containing this: 

```ini
max_execution_time = 7200
max_input_time = 600
max_input_vars = 5000
memory_limit = 256M
upload_max_filesize = 256M
post_max_size = 256M
max_file_uploads = 20
output_buffering = 4096
```

Does the plugin use a different directory context, so these variables are not applied?

My settings: 
<img width="1318" alt="Screen Shot 2021-11-26 at 18 30 50" src="https://user-images.githubusercontent.com/24259245/143615444-570bd0c4-22e8-4b49-87b4-209fd8ca7c58.png">
<img width="1085" alt="Screen Shot 2021-11-26 at 18 30 08" src="https://user-images.githubusercontent.com/24259245/143615448-14df5e77-72f1-40d5-896a-171627ca9ba7.png">

My logs: https://gist.github.com/martin-braun/b77d33036829c30e30bf74bc0138cba4 (really too massive ...)

How can I fix this issue, please?

**Comment by dbccomm** [comment]
I had the same problem, I beleive its the max_execution_time and this could be risky to increase it.
what I REALLY suggest you to do

- install wp-cli
- Create a backup profile with no scedule

wp xcloner_generate_backup --profile=<profile_id>

Works like a charm

To automate the process, add it to your /etc/crontab !

**Comment by martin-braun** [comment]
@dbccomm Great idea, but this server is managed, so I have no SSH access. Also I tried to set `max_execution_time` ridiculously high, so it seems to run exceptionally slow for some reason. 

I already have an extern cron job to trigger WP cron jobs, so I could toggle them off for normal requests.

**Comment by dbccomm** [comment]
Break your backup in parts..

Schedule multiple backup 

the database

uploads/2020

uploads/2021

That could be a solution.

**Comment by martin-braun** [comment]
@dbccomm Really?

<img width="602" alt="Screen Shot 2021-12-16 at 00 04 06" src="https://user-images.githubusercontent.com/24259245/146278690-20459a0d-6541-4d2e-b4dc-afbb84336290.png">

Given those sizes which should be just over 2GB, I doubt this will help. 

`phpinfo()` confirms my changes: 

<img width="948" alt="Screen Shot 2021-12-16 at 00 08 05" src="https://user-images.githubusercontent.com/24259245/146278890-486e4cd6-e5ab-4a97-970e-c08f460ce42e.png">

The possible issue here is that I have to modify the values by placing the php.ini into the directory of context. I also placed it in wp-admin folder to be sure. 

If I understand XCloner, it should trigger a backup segment for each cron job call, which I make sure is called every 5 minutes. I have to find an alternative now, this plugin doesn't work for me.

**Comment by dbccomm** [comment]
Does your script run out of memory ? what is your memory limit set to ?

**Comment by Ars92** [comment]
@jimiero please check if you can reproduce.

**Comment by Ars92** [comment]
@jimiero ^^

**Comment by jimiero** [comment]
I'm not able to reproduce this issue here @martin-braun can you try with our latest version and see how it goes with it?
