### ISSUE TITLE
Multi-parts backups to remote storages issue

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#193]
Seems there's an issue with backups done in multi parts, XCloner uploads only the last backup part to the remote storage, and the others are missing

Steps to reproduce:

1. Go to XCloner settings > System options > 
2. in "Split Backup Archive Limit (MB)" field enter value: 10
3. Save settings 

Run a backup with that remote storage from Watchful

PHP | 7.3.33

MySQL | 5.5.5

**Comment by vdrover** [comment]
Does this happen with all remote storage including FTP?

**Comment by jimiero** [comment]
Closing, is fine with latest version
