### ISSUE TITLE
Automated deploy to WordPress.org

### ISSUE THREAD

**Issue by Shelob9** [watchfulli/XCloner-Wordpress#201]
Talked to @vdrover  yesterday about this and did a bunch of testing today of the 10up deploy action in use here: 

https://github.com/watchfulli/XCloner-Wordpress/blob/master/.github/workflows/main.yml

Concerns:
1. Will it include  vendor dir and built JS/CSS files?
1. Will it exclude config files, test files and other things we do not want to ship to dot org?
1. Can we use the exact same build process as we will use to automate zip file builds? #199

Findings:
> Will it include  vendor dir and built JS/CSS files?
Yes, beacuse we run npm and composer in that workflow, those files will be included.

> Will it exclude config files, test files and other things we do not want to ship to dot org?

This is possible to achive with .distignore file here: https://github.com/watchfulli/XCloner-Wordpress/blob/master/.distignore

Need to double check it.

>  Can we use the exact same build process as we will use to automate zip file builds?

Not exactly. I tried to use Plugin Machine CLI to build plugin into another directory and then upload that to SVN, but it did not work as documented. I will build a solution into Plugin Machine soon, for now, careful cut and paste will be OK.

**Comment by Ars92** [comment]
We were able to deploy a new version of the plugin with GH actions today.
