### ISSUE TITLE
Test new version

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#211]
- [x] Basic Settings can be saved
- [x] Remote Storages settings can be saved and can be validated against valid credentials (spot-test with existing cloud credentials from LastPass)
- [x] Generate Backup - full backup with default settings
- [x] Generate Backup - partial backup with some tables excluded
- [x] Generate Backup - partial backup with some files excludes
- [x] Generate Backup - partial backup with additional databases included
- [x] Generate Backup - full backup with encryption enabled
- [x] Generate Backup - full backup transferred to Dropbox
- [x] Generate Backup - full backup transferred to Dropbox and deleted from local
- [x] Manage Local Backups - Make sure backups are listed.
- [x] Manage Local Backups - Make sure backups can be deleted
- [x] Manage Local Backups - Make sure backups can be uploaded to DropBox
- [x] Manage Local Backups - Make sure backups can be downloaded. 
- [x] Manage Local Backups - Make sure backup contents can be listed.
- [x] Manage Local Backups - Make sure an encrypted backup can be unencrypted.
- [x] Manage Dropbox Backups - Make sure backups are listed.
- [x] Manage Dropbox Backups - Make sure backups can be deleted
- [x] Manage Dropbox Backups - Make sure backups can be uploaded to DropBox
- [x] Manage Dropbox Backups - Make sure backups can be downloaded. 
- [x] Manage Dropbox Backups - Make sure backup contents can be listed.
- [x] Manage Dropbox Backups - Make sure an encrypted backup can be unencrypted.
- [x] Create a Scheduled Profile
- [x] Check the correct recurrence of a scheduled Profile based on the Wordpress cronjob execution
- [x] Trigger any backup profile from the XCloner CLI 
- [x] Restore full backup locally
- [x] Restore full backup to a remote location
- [x] Enable/Disable logs - check if enabling/disabling logs in XCloner works
- [x] Site connects/validates in Watchful (test `Refresh data` success)
- [x] XCloner backup works as expected in Watchful
- [x] Check if XCloner version has been incremented from previous release
- [ ] Check if release has changelog notes

**Comment by jimiero** [comment]
I get this error when trying to setup a sFTP connection:

`[client 86.126.44.23:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught League\\Flysystem\\ConnectionRuntimeException: Could not connect to host: ftp.dev.watchful.net, port:21 in /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Ftp.php:148\nStack trace:\n#0 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(977): League\\Flysystem\\Adapter\\Ftp->connect()\n#1 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(395): Watchfulli\\XClonerCore\\Xcloner_Remote_Storage->get_ftp_filesystem()\n#2 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(363): Watchfulli\\XClonerCore\\Xcloner_Remote_Storage->verify_filesystem('ftp')\n#3 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-res...', referer: https://demo.presswatcher.com/17/wp-admin/admin.php?page=xcloner_remote_storage_page`

**Comment by jimiero** [comment]
I get an error when trying to setup a sFTP connection

`[client 86.126.44.23:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught League\\Flysystem\\ConnectionRuntimeException: Could not connect to host: ftp.dev.watchful.net, port:21 in /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Ftp.php:148\nStack trace:\n#0 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(977): League\\Flysystem\\Adapter\\Ftp->connect()\n#1 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(395): Watchfulli\\XClonerCore\\Xcloner_Remote_Storage->get_ftp_filesystem()\n#2 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Remote_Storage.php(363): Watchfulli\\XClonerCore\\Xcloner_Remote_Storage->verify_filesystem('ftp')\n#3 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-res...', referer: https://demo.presswatcher.com/17/wp-admin/admin.php?page=xcloner_remote_storage_page`

**Comment by Ars92** [comment]
@jimiero 

> FYI: for Dropbox with a valid connection it seems fine, only when it cant connect, has that issue

This means that you receive the same error you wrote about SFTP when you try to setup a Dropbox connection with wrong credentials?

What about all other unchecked items? You haven't tested it yet or they're not working?

Thank you.

**Comment by jimiero** [comment]
@Ars92 the same error happens for other remote storage if you enter a wrong  credentials

I also found an error when trying to download restore script:

[Thu Jun 09 12:11:45.775400 2022] [proxy_fcgi:error] [pid 23119:tid 140055452542720] [client 86.126.44.23:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught splitbrain\\PHPArchive\\FileInfoException: /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/../../restore/vendor.build.txt does not exist in /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/splitbrain/php-archive/src/FileInfo.php:71\nStack trace:\n#0 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/splitbrain/php-archive/src/Tar.php(273): splitbrain\\PHPArchive\\FileInfo::fromPath('/home/demos/web...', 'vendor.phar')\n#1 /home/demos/webapps/wpdemo/public/17/wp-content/plugins/xcloner-backup-and-restore/vendor/watchfulli/xcloner-core/src/Xcloner_Api.php(1363): splitbrain\\PHPArchive\\Tar->addFile('/home/demos/web...', 'vendor.phar')\n#2 /home/demos/webapps/wpdemo/public/17/wp-includes/class-wp-hook.php(307): Watchfulli\\XClonerCore\\Xcloner_Api->download_restore_script('')\n#3 /home/demos/webapps/wpdemo/public/17/wp-include...', referer: https://demo.presswatcher.com/17/wp-admin/admin.php?page=xcloner_restore_page

**Comment by Ars92** [comment]
@jimiero 
I'll provide privately a new version that should fix all your findings (can't upload here as it exceeds maximum upload size).
Thank you.

**Comment by jimiero** [comment]
@Ars92 those two errors are sorted also
