### ISSUE TITLE
Issue with XCloner CLI

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#225]
@Ars92 when i try to run a backup with XCloner CLI it doesn;t do anything seems

While doing it with WP CLI it's fine just showing this warning, which i think is not related with us?

`~/webapps/phpswitches-wordpress/public$ wp xcloner_generate_backup --profile=1
PHP Notice: Constant WP_DEBUG already defined in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/xcloner.php on line 110
Notice: Constant WP_DEBUG already defined in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/xcloner.php on line 110
PHP Notice: Constant WP_DEBUG_DISPLAY already defined in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/xcloner.php on line 111
Notice: Constant WP_DEBUG_DISPLAY already defined in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/xcloner.php on line 111`

**Comment by Ars92** [comment]
@jimiero please test if the attached solves the issue (just test if it solves the issue for you, we don't need a full release test right now).
[xcloner-backup-and-restore-202208221421.zip](https://github.com/watchfulli/XCloner-Wordpress/files/9394265/xcloner-backup-and-restore-202208221421.zip)

**Comment by jimiero** [comment]
@Ars92 seems to be fine, only these php notices

`dev-phpversions@ip-172-26-3-177:~/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore$ php xcloner.php -p 2 -v
PHP Notice:  Trying to get property 'backup_params' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 798
PHP Notice:  Trying to get property 'database' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 799
PHP Notice:  Trying to get property 'excluded_files' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 800

Notice: Trying to get property 'backup_params' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 798

Notice: Trying to get property 'database' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 799

Notice: Trying to get property 'excluded_files' of non-object in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner.php on line 800`

the backup is done
