### ISSUE TITLE
Does not upload to WebDav on owncloud

### ISSUE THREAD

**Issue by sviluppoxyz** [watchfulli/XCloner-Wordpress#23]
H there,
I try to generate backup fro wp to owncloud via webdav protocol. Configuration was ok, but xcloner does not upload inside owncloud folder. Error message regards write permission. Could you help me? Thank

**Comment by ovidiul** [comment]
Do you get any errors in the XCloner logger from it's dashboard?

**Comment by sviluppoxyz** [comment]
Hi, log emails is blank:
Backup Site Url: https://mcult.sviluppo.xyz
<>Error Message: Not Found 

In remote configuration when I fill webdav credetial and check verification, xcloner replies me with cannot write webdav folder.  If I fill a webdav folder that I have just created, it does not give me error. However in this case backup remain in local disk and not transfer in webdav.

**Comment by ovidiul** [comment]
The webdav  folder needs to be created before you can upload to it, if the connection verifies, then that means XCloner is able to upload files to it, however if the backup does not upload there, it could be that the upload connection fails, how did you setup your cron scheduler? Are you using a server based cron scheduler to trigger the backup process as explained here https://www.siteground.com/tutorials/wordpress/real-cron-job/ ?

**Comment by sviluppoxyz** [comment]
No in this moment I am using wpcron

**Comment by vdrover** [comment]
Is this still an issue? Please re-open as needed.
