### ISSUE TITLE
Scheduled backups not working

### ISSUE THREAD

**Issue by Ars92** [watchfulli/XCloner-Wordpress#231]
See https://wordpress.org/support/topic/scheduled-backup-not-working-for-4-40/

As reported by the user, scheduled backups are not working: the class used into the scheduler was recently renamed.
Theoretically we can remove that piece of code that instantiate a new `Xcloner` class since the same class is already instantiated in the constructor.

**Comment by jimiero** [comment]
this is working now with 4.4.2
