### ISSUE TITLE
[SECURITY] Database password stored as plain text

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#234]
In the `Mysql settings`, the site database password is stored as plain text and is easily viewable in dev tools. I assume it's also stored in pkaintext in the database.

We should encrypt this.

**Comment by Ars92** [comment]
Before doing this, I tired to understand why we store Mysql credentials in the first place and it seems to be related to the `XCloner_core` package we made to have common code for different CMS that we abandoned.
If you @vdrover don't recall any other reason to store Mysql credentials into our plugin, I'll just remove these settings.

**Comment by vdrover** [comment]
Maybe related to adding the creds back to a config.php?

**Comment by Ars92** [comment]
Based on Ovidiu email, my guess was correct. I will proceed removing those options.
