### ISSUE TITLE
BulletProof Security prevents backup from completing

### ISSUE THREAD

**Issue by g4570n** [watchfulli/XCloner-Wordpress#236]
For a few versions of the plugin I have not been able to backup my WordPress installation locally.

When the backup is being generated, scanning the file system, the process pauses and gives me a popup with a 500 error.

```
 Código de respuesta: 500 error
 {"readyState":4,"responseText":"<p>Ha habido un error crítico en esta web.</p><p><a href=\"https://wordpress.org/support/article/faq-troubleshooting/\">Aprende más sobre el diagnóstico de WordPress.</a></p>","status":500,"statusText":"error"}
```
This never happened to me before. The last backup without problems that I was able to do was in March of this year.

Sometimes the process ends and it generates a file but it only contains the database backup: 
`backup_domain.com-2022-06-30_00-35-sql-scan_.tgz`

Plugin version: 4.4.3
WordPress version: 6.0.1
PHP version: 7.4.30
PHP Actual Configuration Memory Limit: 512M
WordPress Admin Memory Limit: 512M
WordPress Base Memory Limit: 256M

The site is hosted on shared Hostgator hosting.

**Comment by g4570n** [comment]
The permissions for my files are in: `644 (-rw-r--r--)` and for the folders they are in: `755 (drwxr-xr-x)`

I discovered that if I disable the plugin: `BulletProof Security (version 6.5)`, the problem does not occur. Apparently there is an incompatibility problem between the two, I hope it can be resolved.

**Comment by vdrover** [comment]
TY, we will try to replicate.

**Comment by vdrover** [comment]
https://wordpress.org/plugins/bulletproof-security/

**Comment by vdrover** [comment]
@jimiero please install this plugin and test. https://wordpress.org/plugins/bulletproof-security/

**Comment by jimiero** [comment]
I've just tested this and works as expected here the backup process finishes successfully.
