### ISSUE TITLE
Google Drive plugin causing an fatal error when trying to save settings

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#237]
If you try to setup google drive, when you save the settings for that storage type, it throws an error:

`Fatal error: Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/vendor/guzzlehttp/guzzle/src/functions.php:61 Stack trace: #0 /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-google-drive/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler() #1 /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-google-drive/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create() #2 /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner_Remote_Storage.php(779): GuzzleHttp\Client->__construct() #3 /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/lib/Xcloner_Remote_Storage.php(818): Watchfulli\XClonerCore\Xcloner_Remote_Storage->gdrive_app_fetch_access_token() #4 /home/dev-phpve in /home/dev-phpversions/webapps/phpswitches-wordpress/public/wp-content/plugins/xcloner-backup-and-restore/vendor/guzzlehttp/guzzle/src/functions.php on line 61
`

XCloner version: Version 4.4.3

**Comment by nadsnir** [comment]
Also worked for me when rolling back to 4.2.16, but then B2 doesn't work due to an outdated API.

**Comment by Ars92** [comment]
@dbccomm @nadsnir Fixed with version 4.5.2.
Note that, starting from this version, the separate "XCloner Google Drive" plugin is not needed anymore to use Google Drive storage.
