### ISSUE TITLE
[BACKBLAZE] Can't view remote backups

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#239]
# Observed Behaviour
Backup completes successfully and is uploaded to Backblaze (verified on BB website). But when I try to view the Backblaze backup in the `Manage backups` area, the following error is displayed:

```
DataTables warning: table id=manage_backups - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

# Expected/desired Behaviour
Remote backups should be displayed.

# Specific site/account to reproduce
Account: video.demo
Site: [20 - Wodpress.org](https://app.watchful.net/app/#/dashboard/site/29715)
Note: happens with both PHP 7.4.30 and PHP 8.0.21
XCloner Version: 4.4.3

**Comment by Ars92** [comment]
@vdrover I'm unable to replicate this issue on that site with version 4.4.5.

**Comment by vdrover** [comment]
Getting it right now with XCloner 4.4.6:

watchful account: video.demo
siteID: 107529
site name: 002 - Alliterators Anonymous

Note: need to go to `Manage Backups` and select `backblaze` from the dropdown.

![Uploading php80.watchful.pro says 2022-09-07 at 7.52.53 AM.jpg…]()

**Comment by vdrover** [comment]
Getting it right now with XCloner 4.4.6:

watchful account: video.demo
siteID: 107529
site name: 002 - Alliterators Anonymous

Note: need to go to `Manage Backups` and select `backblaze` from the dropdown.

![php80 watchful pro says 2022-09-07 at 7 52 53 AM](https://user-images.githubusercontent.com/3143313/188883685-27163ec5-e3f5-4c26-bc27-45cb7de907b3.jpg)

**Comment by Ars92** [comment]
For some reason, that bucket on your account is not returning a creation date. I'll prevent this kind of error.
