### ISSUE TITLE
Backup date from backups on backblaze is not valid

### ISSUE THREAD

**Issue by finalwebsites** [watchfulli/XCloner-Wordpress#24]
Hi,

If I select Backblaze in my list of backups (Manage Backups), the date seems to be empty, showing 01 Jan, 1970 00:00.
The local files dates are fine.

![screenshot 2018-07-25 at 08 17 23](https://user-images.githubusercontent.com/90638/43182808-2e94411c-8fe3-11e8-849e-be468fe889a5.png)

**Comment by vdrover** [comment]
Is this still an issue? Please re-open as needed.
