### ISSUE TITLE
[RESTORE] Cloning a site gives 500 error

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#242]
# Observed Behaviour
When restoring a backup on a remote site (i.e. cloning a site), a 500 error occurs and the site goes offline with a critical error. 

Making and restoring a backup on the same saite works as expected.

# Expected/desired Behaviour
We should be able to clone a site without error.

# Specific site/account to reproduce
This was tested multiple times using the video.demo account as follows: 
1. Reset `11 - Another Blog` and `14 - Marketing Microsite` by running the following command via ssh: `~/webapps/unite/reset.sh`. Follow the on-screen prompts to reset sites 11 and 14.
2. Log into the site 11 backend. Create an XCloner backup. 
3. Confirm that the site 11 backup can be restored on site 11.
4. Repeat steps 2 and 3 for site 14.
5. Copy the site 11 backup to site 14. 
6. On site 14, attempt to restore all the files.

# Basic server & app details
 - XCloner version: 4.4.2 on each site.
 - PHP version: tested with both PHP 7.4 and 8.0

# Attachments
![Restore Backups ‹ 14 - Marketing Microsite — WordPress 2022-08-18 at 6 54 56 AM](https://user-images.githubusercontent.com/3143313/185391800-8065b777-ac61-440f-a1b7-827c81737a2e.jpg)
![WordPress › Error 2022-08-18 at 6 55 16 AM](https://user-images.githubusercontent.com/3143313/185391817-4fcb0fc7-98c3-4432-a005-33423af5b7c9.jpg)

**Comment by Ars92** [comment]
Since I was able to perform a restore a site from another site, please include the error logs of the webserver.
Note that when you restore all the files, you're also restoring the configuration file of the other site.
This is likely to break your site if, for example, WP cannot access the same DB used by the first site.
In addition, when you restore the DB of another site in the next step, it's likely that you'll write WP options with URL of the previous site (e.g. the home URL) that will force a redirection of the site that originated the backup.

**Comment by Ars92** [comment]
For this reason we have the options to partially restore a backup, probably we need to document them better.

**Comment by vdrover** [comment]
How did you clone a full site without cloning the config file?

**Comment by Ars92** [comment]
@vdrover I didn't?

**Comment by Ars92** [comment]
I restored site A using the full backup of site B without issues, but site A is able to access database of site B.

**Comment by Ars92** [comment]
Anyway, the "DB question" of the configuration file was only an example.

**Comment by Ars92** [comment]
As I wrote in my first comment, please include the error logs of the webserver.

We probably have to write some code to clean URLs on the DB when cloning a site to another, that was part of the restoration script.

**Comment by vdrover** [comment]
Webserver logs? I'll have to ask you yo look those up. It's the video.demo account and `demos` web server.
