### ISSUE TITLE
[BACKUP] Scan Goes on Indefinitely

### ISSUE THREAD

**Issue by nadsnir** [watchfulli/XCloner-Wordpress#252]
# Observed Behaviour
When generating a new backup, scanning the file system doesn't stop and finds the same files over and over. It shows a file size larger than all files in the site directory. Also generates huge log files because of that.

When trying version 4.2.16 as suggested in issue #237, it worked well, but there the Backblaze API doesn't work, so I can't use it since I want both Google Drive and B2.

Edit: also tried version 4.3.5 from the repository and it did work, but gave a 500 error when trying to upload to B2, same as the error in #237.

# Expected/desired Behaviour
The scan should stop after running through all files.

# Basic server & app details
 - XCloner version: 4.4.7
 - PHP version: 8.1.10
 - WordPress version: 6.0.2

**Comment by nadsnir** [comment]
Edited with two other tested versions (4.2.16, 4.3.5).

**Comment by nadsnir** [comment]
Yes, it's happening with 4.6.0 as well. It works on another site (on the same host), but not on all sites, apparently.

**Comment by vdrover** [comment]
@nadsnir We'll need more info from both sites (the one working and not working). To do this securely, please add both sites to a [free Watchful account](https://app.watchful.net/app/#/join). Once the sites are connected to Watchful, you can submit a secure support ticket and we can troubleshoot.
