### ISSUE TITLE
Unable to use single Application Keys

### ISSUE THREAD

**Issue by JamieSBenson** [watchfulli/XCloner-Wordpress#26]
I'm trying to use an application key specific to this instance to separate backups on multiple WordPress sites, but I'm only able to get this plugin to work when I enter the master key and account Id, which I would really prefer not to do for security reasons. If I use the specific application key and key id with a curl request to B2 it authorizes just fine and sends me back the bucket information, but the plugin gets upset if I put a key Id into the account Id field as opposed to the whole account details... 
All requests other than the master key yield a 401 "Invalid Authorization" error.
Can't find a way around this issue. Please help!

**Comment by vdrover** [comment]
Is this still an issue? Please re-open as needed.
