### ISSUE TITLE
Update `Tested up to` field for 6.3 Live Product Demo

### ISSUE THREAD

**Issue by watchfulli** [watchfulli/XCloner-Wordpress#285]
A new stable version of WordPress has been released: 6.3 Live Product Demo
Please update the WordPress repository for Watchful and XCloner to indicate support for this version in the `Tested up to` field.
https://wordpress.org/news/2023/07/6-3-live-product-demo/

**Comment by Ars92** [comment]
@watchfulli @vdrover this version of WP hasn't been released yet.
