### ISSUE TITLE
Optimize translations

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#315]
Feedback from support forum: https://wordpress.org/support/topic/optimize-translations/

Hi,

I translated the plugin into Dutch this week, but I have a small suggestion in order to optimise the translation work.

You have included the full changelog in the “readme.txt” file. I would suggest taking the same approach as the woocommerce plugin and many others. That is, include only the changelog of the latest minor/major release in the “readme.txt” and put the older changes in a separate file (e.g. changelog.txt). See https://wordpress.org/plugins/woocommerce/#developers

This way the older changelog fixes/releases will not pop up in the translation files.

Regards

**Comment by vdrover** [comment]
@jimiero please reply to user.

**Comment by jimiero** [comment]
Informed customer.
