### ISSUE TITLE
Error Message: Unreadable file encountered: temporary file

### ISSUE THREAD

**Issue by jnbarchan** [watchfulli/XCloner-Wordpress#34]
Not sure where to ask this, so I'm trying here....

Have set up XCloner-Wordpress (4.1.1) on remote-hosted web site.  **Settings** has default of **Enable XCloner Backup Log** to **On**, and default **Force Temporary Path Within XCloner Storage** to **Off**.

Every time it backs up (daily scheduled) I get emailed warning:
```
Backup Site Url: https://www.XXX.yyy
<>Error Message: Unreadable file encountered: /tmp/.xcloner-04afc/xcloner-04afc.log 
```
Strangely, this only seems to happen in scheduled backups, if I run a manual **Generate Backup** I do not get such a warning.

What gives?

**Comment by ovidiul** [comment]
Try and set the "Force Temporary Path Within XCloner Storage" option to On in XCloner Settings->System tab and see if it helps, it could be that your system is deleting the create files in tmp/ folder.

**Comment by jnbarchan** [comment]
@ovidiul 
Thank you for such a prompt response!

Goodness knows why it seems to occur during scheduled but not manual, perhaps it's a timing thing in view of your comment.

I have changed that setting over now, and will see how it goes in the scheduled.

*However*: I note that from the **Dashboard** it now says:
```
Temporary Location: /my-hosted-root/htdocs/wp-content/backups/.xcloner-8ccd6
```
Meanwhile my **Regex Exclude Files** has the default:
```
(wp-content\/updraft|wp-content\/uploads\/wp_all_backup)(.*)$
(.*)\.(svn|git)(.*)$
wp-content\/cache(.*)$
(.*)error_log$
```
That does not seem to me to exclude the new temporary location (and, for that matter, that directory is also where it puts all its backups, never mind temporary).  Won't it include its own backups in its backups?  Do I need to add that folder to the excludes, or does XCloner known already not to include its own backup folder regardless of these excludes?

**Comment by ovidiul** [comment]
XCloner won't include it's own backups or at least that's how it should be, it adds the Storage Path for exclusion by default. But feel free to double check, there is always a bug ready to get fixed ;)

**Comment by jnbarchan** [comment]
OK, now we have a different issue.

I have changed over to **Force Temporary Path Within XCloner Storage**.  I do a manual backup (from **Generate Backups**), which includes both the file system and the database.

After the backup has concluded, I look in `/wp-content/backups` and now see 2 `.xcloner-12345` sub-directories still in existence:

* The (slightly) earlier one, which maybe is for the file system files backup, is empty.

* The later one contains files: `database-backup.sql`, `xcloner-49274.log`, `.database`, `backup_files.csv`, `index.html`.

This will obviously begin to accumulate over time.  Should those directories & files have been deleted?  When it runs scheduled instead of manual will that make any difference and it will be cleaned up then so I need not worry?

Thank you for your interest!

**Comment by ovidiul** [comment]
The left over directories are usually deleted when a scheduled backup is executed, the directories are left there if for some reason the backup process is being stopped.

As for the database error, you need to check the mysql user permissions, it seems it's unable to read the tables data, in which case your database backup might be incomplete.

**Comment by jnbarchan** [comment]
Well I can only say that from what I have seen, without any "stopping", manual is leaving them.  I will delete now, and see what happens during scheduled.

I am happy to look into the database permission, but the messages read:
```
the PROCESS privilege(s) for this operation [""] []
```
I was hoping for some hint about the table/operation?  Does that message come simply from the database or does XCloner generate it?

**Comment by ovidiul** [comment]
XCloner has a "show tables" query which might fail with that error if it doesn't have permissions to read the database tables list. 

Please check which grants are enabled for your mysql user https://serverfault.com/questions/117525/how-can-i-show-users-privileges-in-mysql
