### ISSUE TITLE
Asymmetrical Backup Encryption using Public/Private Key

### ISSUE THREAD

**Issue by ovidiul** [watchfulli/XCloner-Wordpress#36]

**Comment by vdrover** [comment]
@ovidiul what's this about?

**Comment by ovidiul** [comment]
I would say that yes.

Right now, the encryption key of the backup is being stored inside the XCloner Settings, so anybody with access to the backend can download and decrypt the backup using that key.

An asymmetrical encryption option would allow the user to save only the public key, while the private key would be kept in a separate location, so a third party user, with backend access, could not decrypt the backup. with just the public key.

So, in the long run, this would be the safest solution to encrypt a backup.

**Comment by vdrover** [comment]
Cool. Let's think about this for 4.2.2.

**Comment by vdrover** [comment]
closing for now.
