### ISSUE TITLE
Database export doesn't export emojis properly

### ISSUE THREAD

**Issue by mravery** [watchfulli/XCloner-Wordpress#38]
Steps to reproduce:

1. Confirm that the database is configured with  'utf8mb4'. 
1. Create a WordPress post/page with an emoji.
1. Create a backup using XCloner. Note that the emoji isn't there in the database sql file.
1. Use `mysqldump --default-character-set=utf8mb4 -u user -p database > mysqldump.sql` to create another backup.
1. Compare to see that the `mysqldump` command preserves the emoji but XCloner doesn't.

**Comment by vdrover** [comment]
@jimiero can u try to reproduce please?

**Comment by jimiero** [comment]
Seems issue still there?

See attached print

![Screen Shot 2020-05-04 at 8 55 02 PM](https://user-images.githubusercontent.com/3626762/80997144-94e4c980-8e49-11ea-8ba6-2db49aeb25d5.png)

**Comment by vdrover** [comment]
What was your testing procedure?

**Comment by jimiero** [comment]
I edited an article, added that emooticon " :) "  checked site frontend and emoticon was displayed.

Took a backup, checked the sql file and there is no " :) " in article text
