### ISSUE TITLE
Add incremental extended inserts 

### ISSUE THREAD

**Issue by iBook140** [watchfulli/XCloner-Wordpress#39]
Hello,

this is a feature request to speed up SQL import. Please add incremental extended inserts as described here:
https://wordpress.org/support/topic/problems-importing-database/#post-12031015 

Thanks in advance and kind regards
René

**Comment by vdrover** [comment]
@ovidiul thoughts?

**Comment by ovidiul** [comment]
This would most probably create issues with incremental mysql restores and php memory limits, we could probably give it some more research to see if it worth adding it.

**Comment by vdrover** [comment]
Thanks @ovidiul . I'll open a separate issue for that.
