### ISSUE TITLE
Unable to connect WebDAV with a " in the password

### ISSUE THREAD

**Issue by darkvadd7** [watchfulli/XCloner-Wordpress#41]
Hi,

I'm trying to connect with WebDAV, but I have a " in my password and the plugin cut the password and doesn't want to connect.

**Comment by ovidiul** [comment]
I am unable to confirm this issue, do you get any specific authentication error?

**Comment by darkvadd7** [comment]
Here is what I do:
1. Got to Remote Storage and complete WebDAV Storage (with my 32 characters password with a " in 4th position): Message "WebDAV storage settings saved.".
2. Then I click on "VERIFY" button: the hidden displayed password is 3 length (characters before "), and I have the message: "WebDAV connection error: Could not write data".

**Comment by ovidiul** [comment]
I am unable to duplicate the issue here so maybe it's server related, have you tried escaping your password?

**Comment by darkvadd7** [comment]
I just tried on Fedora with the last version and seems to work. Thanks!
