### ISSUE TITLE
Confusing user experience when restoring a public site to a local site

### ISSUE THREAD

**Issue by reclaimed** [watchfulli/XCloner-Wordpress#43]
In an attempt to clone the public site to my localhost to play with, I found the operation rather confusing (or unclear). 

1. Entered "Url to XCloner Restore Script": _http://localhost.test/xcloner_restore.php_
2. Pressed "Check Connection":  **Validation ok.**
3. Pressed "Upload": **CURL communication error with the restore host. We have received no valid response from the remote host, original message: **

I believe the second step has checked the connection using JS, while the third step relies on PHP to copy data. It's confuses the user and looks like a user's mistake, not the host accessibility issue. A hint or two would make the troubleshooting way easier (and please, add an option for restoring backups to isolated websites).

Good job, Liuta, thanks!

**Comment by vdrover** [comment]
@reclaimed Can u recommend some hints to use? How did u solve this problem?

**Comment by reclaimed** [comment]
@vdrover Thank you for asking! I ended up using the VPN to access the localhost from the web. As for the existing script, the connection checking (step 2 above), if done on the backend, will show possible connection issues before the user starts the transfer.

I planned to implement a cloning tool with the client-side transfer agent: agent.js in the browser requests WP files from the source host's reader.php and sends them to the remote host's writer.php. However, I'm not familiar with CORS and not sure I'll ever finish this idea.

**Comment by ovidiul** [comment]
@vdrover since the XCloner restore is API based, it would be interesting to provide the users with a standalone restore client, could be a JS application that can be run in any browser, and users could access it directly from the restore endpoint xcloner_restore.php currently. 

Right now, we throw an access error, but it could be a nice interface to handle the restore from.

**Comment by vdrover** [comment]
Thanks for your notes @reclaimed !

@ovidiul I'll open a separate issue for that script.
