### ISSUE TITLE
pull and push might be great way?

### ISSUE THREAD

**Issue by alexlii1971** [watchfulli/XCloner-Wordpress#44]
Hello,

It is works great for backup file, but it seems not work for restore.

Pull/push might be a great way/idea to improve the process of migration.

I found there is an plugin at https://github.com/cloudverve/wp-sync-db

and just for your reference, thanks.

**Comment by vdrover** [comment]
@ovidiul Thoughts?

**Comment by ovidiul** [comment]
The WP-sync-db  has a more granular restore option tailored to WP, and yes, while it's nice to have, it might not be the XCloner purpose, which is tailored to be a more bulk restore tool for when you want an exact site replica restore. 

XCloner does have a restore bug that needs to be fixed, where, if a user does a live DB restore, they manage to replace the wp_options table and restore crashes while the user gets logged out.

**Comment by vdrover** [comment]
OK, i'll close this and open an issue related to the bug u menteioned.

**Comment by alexlii1971** [comment]
Thanks.

I tried several times, but I can not restore the Multisite,  I suppose it does not support Multisite yet?

If yes, it would be great if you could take this feature as priority, thanks.
