### ISSUE TITLE
Local files not deleted after transfer to remote location

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#46]
I've been testing the latest version of XCloner. In the settings I enabled "delete backup after remote storage transfer", but the local files remain.

**Comment by vdrover** [comment]
@jimiero please test.

**Comment by jimiero** [comment]
Seems to me this may work, what I found instead is if you check in site backend for your backups  in your remote storage, it dosn't load the backups, probably related with the javascript error in the error console

![Screen Shot 2020-05-04 at 9 09 38 PM](https://user-images.githubusercontent.com/3626762/80999828-f444d880-8e4d-11ea-895e-cb2c97a2a6a7.png)

**Comment by ovidiul** [comment]
There is a also a small JS bug here, so when you don't have a backup created and Manage Backups is empty, the interface doesn't remove the Loading... text

**Comment by vdrover** [comment]
@ovidiul Would you please assign this to milestone v4.2.0 ?

**Comment by vdrover** [comment]
I will close then, and create a new issue for the JS bug.
