### ISSUE TITLE
[Xcloner_Standalone] Remove schedule params from configuration

### ISSUE THREAD

**Issue by Ars92** [watchfulli/XCloner-Wordpress#50]
Since `Xcloner_Standalone` in not used to schedule a new backup, `schedule` is useless and, in fact, overwrites some other parameters such as the database name that is already specified in the option named `xcloner_mysql_database`.
The schedule option object could be converted in a set of "options".

**Comment by ovidiul** [comment]
The schedule parameter contain some specific backup options, for instance, if the user wants to backup additional databases, which remote storage to send it to,  which files to exclude and so on. While i agree the schedule is not the best name for the parameter, it has it's own usability in creating the general backup start config.

**Comment by Ars92** [comment]
We are trying to maintain consistency and order in all the code we write to make it easy to understand and maintain.
The `schedule` option value is completly different from the others and its intent is not clear.
As mentioned earlier, I think that there is an issue: the option named `xcloner_mysql_database` specifies a database name but also the `schedule->database` parameter. If the user wants to backup additional database we should be able to specify the names in the `xcloner_mysql_database` option.
Anyway, If those parameters are really used to configure a backup just transform that JSON that is inside the `schedule` option into a set of options.
For example:
`schedule->backup_params->backup_name`
should become another option object to be inserted in the configuration:
`{"option_name":"backup_name","option_value":"some_name"}`

**Comment by ovidiul** [comment]
The schedule option is now renamed to backup profile, i think it makes much more sense, each backup, before it's generated, can have it's own profile beside the global config parameters. To avoid the code boilerplate, this structure is already compatible with the schedule one, so no other changes are requires in the main XCloner plugin.
