### ISSUE TITLE
Improve language string for `backup before update` tooltip

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#55]
In looking at this tooltip in the settings, I don't think it's currently accurate. 

<img width="947" alt="Screen Shot 2020-05-04 at 11 30 27 AM" src="https://user-images.githubusercontent.com/3143313/80989784-06e1f200-8dfb-11ea-955b-e4b5953edf56.png">

Per conversation with @ovidiul a backup is only triggered when a core file is updated. So I think the language string should be:

`Attempt to generate a full site backup before applying automatic core updates.`

Is that accurate?

**Comment by ovidiul** [comment]
References updated in milestone4.1.4 branch

<img width="795" alt="Screenshot 2020-05-05 at 07 32 39" src="https://user-images.githubusercontent.com/537751/81035194-9e4e5000-8ea2-11ea-9e7f-52489e18dddc.png">
