### ISSUE TITLE
Move `send to remote destination` option to the `Backup Options` tab

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#56]
As discussed on email with @ovidiul , the `send to remote destination` option should be moved from the `schedule tab` to the `backup options` tab as sown below: 

<img width="1003" alt="Image 2020-05-01 at 4 53 04 AM" src="https://user-images.githubusercontent.com/3143313/80990359-d484c480-8dfb-11ea-8d8e-b1f09cc0fd19.png">

Some considerations:
1. We need some sort of progress indicator for the remote destination upload. This should appear on the 'Generate Backup' tab after the existing progress indicators.
2. We should add a new option on the `Backup Options` tab to delete the local copy after uploading to the remote destination as shown above. This option would only display if `send to remote destination` is enabled.
3. Changes should not affect Watchful's current implementation of remote destination support.

**Comment by vdrover** [comment]
Progress indicator: 
![unnamed (5)](https://user-images.githubusercontent.com/3143313/81002797-7366ec00-8e0f-11ea-84b4-4f69b5b9e10e.png)

**Comment by vdrover** [comment]
Progress indicator for remote file transfer from Akeeba CLI:
![Image 2020-05-04 at 1 58 41 PM](https://user-images.githubusercontent.com/3143313/81002867-8ed1f700-8e0f-11ea-83c0-a6e827ee3c91.png)

**Comment by ovidiul** [comment]
@1 Progress lightbox has been added on the generate backup page to automatically start the transfer when remote storage option is selected

@2 done, option added as well on the manage schedule area

@3 i don't see any issues here, but please confirm

<img width="783" alt="Screenshot 2020-05-20 at 13 18 12" src="https://user-images.githubusercontent.com/537751/82446580-8f28ee00-9aaf-11ea-8e44-91fd5effdd17.png">
<img width="760" alt="Screenshot 2020-05-20 at 13 18 35" src="https://user-images.githubusercontent.com/537751/82446586-918b4800-9aaf-11ea-9cba-1123c586083a.png">

**Comment by vdrover** [comment]
I think it looks right. Can I test?

**Comment by vdrover** [comment]
Implemented perfectly.
