### ISSUE TITLE
Update footer in progress indicator

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#57]
Let's update this footer:

<img width="759" alt="Image 2020-05-04 at 11 44 58 AM" src="https://user-images.githubusercontent.com/3143313/80991637-eff0cf00-8dfd-11ea-992a-b89a56d11b13.png">

Please switch the twitter account to: `https://twitter.com/WatchfulDashbrd`

**Comment by ovidiul** [comment]
References updated in milestone4.1.4 branch

<img width="863" alt="Screenshot 2020-05-05 at 07 32 05" src="https://user-images.githubusercontent.com/537751/81035173-8971bc80-8ea2-11ea-9a35-a27cfc096db4.png">
