### ISSUE TITLE
Update developer link in the plugins area of site backend

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#58]
The plugin area is not respecting the plugin owner from the WP repo: 

<img width="678" alt="Image 2020-05-04 at 11 58 24 AM" src="https://user-images.githubusercontent.com/3143313/80992127-abb1fe80-8dfe-11ea-84f8-98c308bafec6.png">

As you can see, this is working as expected for the Google Drive XCloner plugin.

**Comment by ovidiul** [comment]
References updated in milestone4.1.4 branch

<img width="892" alt="Screenshot 2020-05-05 at 07 15 47" src="https://user-images.githubusercontent.com/537751/81034592-529aa700-8ea0-11ea-886d-5793e27f1a83.png">
