### ISSUE TITLE
Differential from last backup date

### ISSUE THREAD

**Issue by AmibeWebsites** [watchfulli/XCloner-Wordpress#6]
Enhancement suggestion.

I can imagine selecting another scheduled backup the source of the schedule differential time (or 'this scheduled backup', resulting in incremental backups). That way the differential can be from when the last scheduled backup ran.

For example, one full backup scheduled per week and one differential backup from when the last full backup ran (scheduled daily).

**Comment by skibulk** [comment]
+1

**Comment by vdrover** [comment]
We have concerns about reliability on this front. We may circle back on this, but for now we'll close the issue.
