### ISSUE TITLE
Add standalone CLI

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#60]
As discussed, we'd like a standalone CLI script to be able to generate backups from the command line and via crontask. This may necessitate saving a "profile" which can be specified as a CLI attribute. 

1. One approach might be to use the existing `scheduled` backups as profiles than can be triggered via CLI. If you go this route, it may be an idea to add a `None` option to the backup frequency dropdown so that a profile can be saved and run from CLI, but not necessarily scheduled.

2. I'm happy to also have this integrate with WP-CLI. If that needs a separate issue and/or milestone, please create the needed issue/milestone as appropriate.

**Comment by ovidiul** [comment]
1. I have implemented this route by adding the "Manual Execution" profile to the Schedule Frequency list, to launch it, a user would need to execute:

php ..../wp-content/plugins/xcloner-backup-and-restore/xcloner.php profile_name_here_or_ID

<img width="587" alt="Screenshot 2020-05-27 at 09 11 57" src="https://user-images.githubusercontent.com/537751/82984381-becd7e00-9ffa-11ea-907f-e0c632f7ba95.png">
<img width="612" alt="Screenshot 2020-05-27 at 09 12 06" src="https://user-images.githubusercontent.com/537751/82984393-c2f99b80-9ffa-11ea-91fa-fade64715ae2.png">
<img width="1119" alt="Screenshot 2020-05-27 at 09 16 44" src="https://user-images.githubusercontent.com/537751/82984408-cd1b9a00-9ffa-11ea-9e69-785a01eb2918.png">

2. wp-cli integration should be done in a new milestone as it has it's own complexities

**Comment by vdrover** [comment]
I can't wait to test this! Can we rename `Manual Execution` to simply `Manual`?

**Comment by vdrover** [comment]
I tested the cli and generating a backup worked fine. The output was VERY verbose. Should we consider something a little more "viewable"? 
```
Scanning the filesystem...
Generating MySQL backup...
Adding files to archive...
Sending backup to Dropbox...
Cleaning up...
Process complete.
```

Also, i did notice one error:
`[2020-05-27 12:55:32] xcloner_scheduler.ERROR: SplFileInfo::getType(): Lstat failed for /home/demos/webapps/wpdemo/public/31/wp-content/backups-dAZXp/backup_demo.presswatcher.com-2020-05-27_12-55-sql-c7766.tar [] []`
Expected?

**Comment by ovidiul** [comment]
Option added as -v

<img width="892" alt="Screenshot 2020-05-27 at 18 13 00" src="https://user-images.githubusercontent.com/537751/83038582-cd8d5280-a045-11ea-8ee4-94bad393077e.png">

Added -h and -p <profile name>  as additional options

<img width="775" alt="Screenshot 2020-05-27 at 18 20 30" src="https://user-images.githubusercontent.com/537751/83039409-cfa3e100-a046-11ea-88c2-7ec27d0dfae0.png">

**Comment by ovidiul** [comment]
The error is not expected, can you give the context of that log line to see where it had appeared?

**Comment by vdrover** [comment]
I appeared towards the end of the verbose output. If there is a CLI log file, I can send it along.

**Comment by vdrover** [comment]
<img width="1533" alt="Image 2020-05-27 at 1 57 52 PM" src="https://user-images.githubusercontent.com/3143313/83061153-277c2100-a022-11ea-8307-e735130dbd0f.png">

**Comment by vdrover** [comment]
I updated my branch but got the message `Already up to date.`. -h and -v not working for me yet.

**Comment by ovidiul** [comment]
Please try again now, the Lstat error is 'normal' since the file has been deleted after the remote transfer.

**Comment by vdrover** [comment]
-h and -v still not working for me.

**Comment by vdrover** [comment]
Working perfectly now that I deleted the plugin and cloned the repo again.
