### ISSUE TITLE
Add additional cleanup & quota options for backup storage

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#61]
Is it possible to add the following cleanup options to the remote storage destinations?

'Cleanup by quantity`
`Cleanup by capacity`
`Never delete backups taken on the ____ day of the month`

And add this to the plugins settings `Cleanup` area:
`Never delete backups taken on the ____ day of the month`

**Comment by ovidiul** [comment]
"Never delete backups taken..." option has been added to XCloner backend, @vdrover , i propose to change the naming to "Keep Backups Taken On Month Days" to allow us to put the end box in a logical order, will that be ok for you?

<img width="969" alt="Screenshot 2020-05-13 at 13 15 28" src="https://user-images.githubusercontent.com/537751/81800665-db0ded00-951b-11ea-89a5-6b7e11b28f65.png">


Remote storage cleanup options added as well

<img width="718" alt="Screenshot 2020-05-13 at 13 15 52" src="https://user-images.githubusercontent.com/537751/81800732-f7118e80-951b-11ea-85f1-18c43cb5f8b6.png">

however we need to do more testing across all supported storages, can @jimiero help us with testing?

**Comment by watchfulli** [comment]
Yes, if you provide a package, we can do some testing. I like what I see for these cleanup options, especially that you can have different cleanup for different destinations.

**Comment by vdrover** [comment]
Yes, if you provide a package, we can do some testing. I like what I see for these cleanup options, especially that you can have different cleanup for different destinations.

**Comment by vdrover** [comment]
@ovidiul How does the cleanup work for remote destinations: triggered via WP_cron like the scheduled backups?

**Comment by ovidiul** [comment]
They are triggered as soon as a backup is uploaded to the remote storage, but we can add them in the schedule interface as well, package is here https://github.com/watchfulli/XCloner-Wordpress/archive/milestone4.2.0.zip

**Comment by vdrover** [comment]
@ovidiul Adding triggers to the `scheduled backups` interface makes sense. But shouldn't we also be checking for quotes independent of generating a backup?

**Comment by vdrover** [comment]
@jimiero Please see the latest release. Can you suggest some tests to see how this feature is working?

**Comment by vdrover** [comment]
@ovidiul can we add the tooltips from the settings to each of the remote storage options?

**Comment by vdrover** [comment]
I've devised some tests for the quotas. Here's the overall process:

1. Configure sites with v4.2.0
2. Configure dropbox.
3. Configure crons.
4. Schedule daily backups
5. Record backups saved/deleted on [spreadsheet](https://docs.google.com/spreadsheets/d/1ojMLCgd6V3lCKbbh4kIPBOEJq-TW8ATibBWDXa5Q4qE/edit#gid=0).

As you can see below, my first test is to keep 4 backups at most, but always keep backups taken on the 22nd and 23rd days of the month.
 
Results will be available by 5/26.

## Test 1 - Local Quotas
<img width="518" alt="Image 2020-05-20 at 7 45 20 AM" src="https://user-images.githubusercontent.com/3143313/82447539-0f2e6400-9a6e-11ea-9fcb-eea8a963640c.png">

## Test 2 - Dropbox
<img width="502" alt="Image 2020-05-20 at 7 47 17 AM" src="https://user-images.githubusercontent.com/3143313/82447624-253c2480-9a6e-11ea-8657-efdb842d9d62.png">

**Comment by vdrover** [comment]
@ovidiul I think you said yesterday that you removed the Cleanup Options from the Settings. Can't we keep them there and have them apply to local storage cleanup?

**Comment by vdrover** [comment]
Testing is proceeding. I added in the ability to test the 'remove local backup after remote transfer` and it appears to be working as u  can see below. 

As for quotas, tomorrow both the local and dropbox tests will reach their quotas of 4 files. On Sunday we will hopefully start to see older archives being remvoed. 

<img width="515" alt="Image 2020-05-22 at 10 34 42 AM" src="https://user-images.githubusercontent.com/3143313/82684231-da5e1080-9c17-11ea-845e-7653894ba14b.png">
 
<img width="669" alt="Image 2020-05-22 at 10 32 13 AM" src="https://user-images.githubusercontent.com/3143313/82683993-86532c00-9c17-11ea-880c-fd410edd06cb.png">

**Comment by vdrover** [comment]
Testing update: the `remove local backup after remote transfer` appears to be working as expected, and local quotas also. However, in my remote quota test there should only ever be 4 files stored on Dropbox. As you can see below, I see 5 on Dropbox currently. The remote delete is working however as I do see that the 5/20 archive has been deleted. 

<img width="687" alt="Image 2020-05-25 at 8 38 25 AM" src="https://user-images.githubusercontent.com/3143313/82818077-c7d81700-9e63-11ea-9189-3a942de8cd65.png">

I suspect that there is some timing issue between when a backup is transferred vs. when the files are counted and the quote applied. If that's true, tomorrow should show 5 files also with the 5/21 archive deleted.

**Comment by vdrover** [comment]
These are working essentially as expected. Will do a a second test once 4.2.0 is released including more remote destinations.
