### ISSUE TITLE
Exclude `docs` folder from releases

### ISSUE THREAD

**Issue by watchfulli** [watchfulli/XCloner-Wordpress#63]

**Comment by ovidiul** [comment]
Fix is posted in the [.distignore](https://github.com/watchfulli/XCloner-Wordpress/blob/master/.distignore) file, we need to test this again to make sure it's working when we publish the new milestone.

**Comment by ovidiul** [comment]
"docs" folder has been excluded from latest release

<img width="977" alt="Screenshot 2020-06-01 at 11 15 13" src="https://user-images.githubusercontent.com/537751/83389646-39323f80-a3f9-11ea-8823-1ad8d35d69a6.png">
