### ISSUE TITLE
Move `delete` button above list of backups

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#64]
Is there any reason we are not using the standard WP interface for the `Manage Backups` and `Schedule Backups` areas? I see why there is a unique interface for the other sections, but these two seem useful for default interfaces.

Thoughts?

**Comment by vdrover** [comment]
The reasons I am considering this:
1. User familiarity
2. Ability to bulk-modify backups or schedules.

**Comment by ovidiul** [comment]
Hi Victor, the main reason is that when i first developed this, it was much easier to just go ahead with the UI framework across all interface to make it look more unified, WP has for sure it's own advantages, and we could switch to that as needed, probably we need to review the API integration there as well to make sure the frontend is fully decoupled from backend.

**Comment by vdrover** [comment]
Is it possible to add some bulk tools to the existing UI? `Send to remote` and `Delete` would be high on the bulk functionality.

**Comment by ovidiul** [comment]
Until we find a solution to incrementally send backups to a remote location , adding a bulk option there would be of not much use. I would suggest to try first and find a solution there and then implement the bulk option .

The Delete option already has the bulk mode activated(checkbox near Backup Name header), or maybe i am missing something here?
<img width="186" alt="Screenshot 2020-05-12 at 12 40 06" src="https://user-images.githubusercontent.com/537751/81668709-bb0ff800-944d-11ea-8d3e-47c504e508b8.png">

**Comment by vdrover** [comment]
@ovidiul I missed the DELETE button at the bottom. Moving this to the top (more where a WP user would look) and making it `unclickable` (greyed-out) unless a backup was selected would help alot. Is that reasonable?

**Comment by vdrover** [comment]
closing for now.
