### ISSUE TITLE
New settings option: delete remote file when deleting backup

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#66]
It would be great to have new parameter in the `settings` area. When enabled, a remote backup file would be deleted when the record was deleted from the `Manage Backups` area. This parameter would be disabled by default.

**Comment by jimiero** [comment]
@vdrover I think this should be more like:

allow to delete file and keep backup record in the list just to know there was a backup done on that date.

So instead one delete button have this flow:

1. Select backup in the list click on "Delete backup " ( which deletes both backup in the list and remote file )

2. Select backup in the list click on "Delete backup file"

**Comment by vdrover** [comment]
@jimiero I have some thoughts on that, but waiting to discuss with @ovidiul about the existing UI in #64. Depending on how that goes, I'll think more about the delete options.

**Comment by vdrover** [comment]
I'm going to close this in favor of switching to the remote backup destination.
