### ISSUE TITLE
Modifying backup properties corrupt tables list

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#67]
Details here:

https://wordpress.org/support/topic/modifying-backup-properties-corrupt-tables-list/#post-12815553

![Screen Shot 2020-05-12 at 9 11 18 AM](https://user-images.githubusercontent.com/3626762/81670247-00cdc000-9450-11ea-827b-fb1ecc14151a.png)

**Comment by vdrover** [comment]
@jimiero Have you reproduced this issue?

**Comment by ovidiul** [comment]
I was able to duplicate this issue, basically, to reproduce it:

1. expand the database tables list in xcloner generate backups tab
2. save the schedule
3. try and edit the saved schedule
4. the result is that the table names get corrupt, in which case the database backup file will exclude them all

I have posted a fix, in the milestone 4.2.0 package
