### ISSUE TITLE
Small JS bug in Manage Backups interface

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#68]
There is a also a small JS bug here, so when you don't have a backup created and Manage Backups is empty, the interface doesn't remove the Loading... text

**Comment by ovidiul** [comment]
Fix is now posted to the current milestone branch

<img width="782" alt="Screenshot 2020-05-13 at 13 12 06" src="https://user-images.githubusercontent.com/537751/81800374-6935a380-951b-11ea-8028-fde7d8c93e6f.png">

**Comment by vdrover** [comment]
Excellent. I noticed this the other day and thought maybe the remote destination had the error.

**Comment by ovidiul** [comment]
It should be gone from Remote destination as well as it's the same interface, just the api endpoint data is different

**Comment by vdrover** [comment]
fix confirmed.
