### ISSUE TITLE
Live DB restore replaces WP Options table

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#69]
XCloner has a restore bug. If a user does a live DB restore, they manage to replace the wp_options table and restore crashes while the user gets logged out.

**Comment by ovidiul** [comment]
Posted a fix into milestone 4.2.0 , seems the issue comes from replacing the data from wp_usermeta table, session_tokens option, so as a fix, i am renaming the table on restore and replacing it with the restored data only in the last step.

**Comment by vdrover** [comment]
No longer being logged out during local restore.
