### ISSUE TITLE
Select to include using Regex

### ISSUE THREAD

**Issue by AmibeWebsites** [watchfulli/XCloner-Wordpress#7]
Feature suggestion.

Option to include/exclude in backup set based on Regex, for both database tables and files.

**Comment by vdrover** [comment]
@ovidiul Is this still relebant?

**Comment by ovidiul** [comment]
Yes, right now we only use regex for exclusion, but the inclusion based on this would also be relevant.

**Comment by vdrover** [comment]
Also, we have this in the settings, but not in the `Generate backup` area. Let's think about this for v4.2.2.
