### ISSUE TITLE
SFTP bug

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#72]
Looks like the most recent release has an SFTP bug: 
https://wordpress.org/support/topic/after-update-to-4-1-4-cannot-connect-to-sftp-site-anymore/#post-12829391

I confirmed this also. Might need a quick release for this.

**Comment by ovidiul** [comment]
I've posted a fix in milestone 4.1.5,  https://github.com/watchfulli/XCloner-Wordpress/archive/milestone4.1.5.zip, can you test this package and see if it works? Seems it was a small type on the config details

**Comment by vdrover** [comment]
@ovidiul fatal error after installing and trying to activate: 
```Fatal error: Cannot redeclare activate_xcloner() (previously declared in /home/xcoloner/webapps/xcloner-dev/public/wp-content/plugins/xcloner-backup-and-restore/xcloner.php:46) in /home/xcoloner/webapps/xcloner-dev/public/wp-content/plugins/XCloner-Wordpress-milestone4.1.5/xcloner.php on line 48```

**Comment by jimiero** [comment]
I tested this and worked fine with 4.1.5

**Comment by vdrover** [comment]
Yes, works for me.
