### ISSUE TITLE
Running a backup and sending to remote store ex, sFTP does not upload the backup file

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#73]
When I run a backup using version 4.2.0 and sending to remote store ex, sFTP 

It does not upload the backup file, even if it says the backup file was uploaded

![Screen Shot 2020-05-14 at 4 00 33 PM](https://user-images.githubusercontent.com/3626762/81937246-11229e00-95fc-11ea-9226-487f9485af33.png)

When I check sFTP, the backup folder is empty, no backup uploaded

**Comment by vdrover** [comment]
This is working fine for me. 
<img width="1454" alt="Image 2020-05-14 at 8 45 39 AM" src="https://user-images.githubusercontent.com/3143313/81942221-7906c380-95bf-11ea-8734-b2e53e2377e0.png">

**Comment by vdrover** [comment]
closing
