### ISSUE TITLE
Javascript error when running a backup, and clicking "Send Backup to remote storage"

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#74]
With version 4.2.0.

When I run a backup, wait backup to get finalized, and then clicking on "Send Backup to remote storage" it throws a javascript error in browser error console, making the buttons now working

![Screen Shot 2020-05-14 at 4 24 00 PM](https://user-images.githubusercontent.com/3626762/81939737-614f2f80-95ff-11ea-8973-af5262869221.png)

**Comment by watchfulli** [comment]
Which backup storage destinations did u test?

**Comment by jimiero** [comment]
Tried with sFTP and WebDav

**Comment by ovidiul** [comment]
I can confirm the bug, posted a fix now in the 4.2.0 milestone package.

**Comment by jimiero** [comment]
I tested this with the new 4.2.0 package in milestone, and seems fine now.

**Comment by vdrover** [comment]
fix confirmed.
