### ISSUE TITLE
Update Remote Storage names

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#77]
S3 Storage >> Amazon S3 Storage
Backblaze Storage >> Backblaze B2 Storage

<img width="364" alt="Image 2020-05-18 at 3 57 50 PM" src="https://user-images.githubusercontent.com/3143313/82259065-9968b200-9920-11ea-8e90-e06a9679fb0d.png">

**Comment by ovidiul** [comment]
Text has been updated

<img width="376" alt="Screenshot 2020-05-20 at 10 15 42" src="https://user-images.githubusercontent.com/537751/82416574-ec5a7a80-9a82-11ea-9dd5-71a87cf3370b.png">

**Comment by vdrover** [comment]
Confirmed.
