### ISSUE TITLE
Update default regex exclusions

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#78]
I was wondering if we might update the regex exclusions list by modifying the first line as follows. 

`(wp-content\/updraft|wp-content\/ai1wm-backups|wp-content\/plugins\/akeebabackupwp\/app\/backups|wp-content\/uploads\/wp_all_backup)(.*)\.(.+)$(?<!(php|html|config))`

In addition to updraft and wp al backup, this change excludes Akeeba Backup and All in 1 WP Backup archives. It also INCLUDES any .php files, .html files and .config files that might be in the excluded directories.

Sometimes these folders have their own `.htaccess` files. Can we not exclude those also?

**Comment by vdrover** [comment]
Additionally, we should probably exclude and `xcloner-xxxx` folders in the site root.

**Comment by ovidiul** [comment]
Hi Victor, rules have been added, please note, they only take effect on new website installs, so to properly test this, you might need to fully delete XCloner options from wp_options table

All files within those folders will be excluded automatically, including .htaccess, php, html and config

<img width="700" alt="Screenshot 2020-05-20 at 10 33 05" src="https://user-images.githubusercontent.com/537751/82418312-83283680-9a85-11ea-8de6-e366b608f03b.png">

**Comment by ovidiul** [comment]
xcloner-xxxxx folder added as well for exclus
<img width="774" alt="Screenshot 2020-05-20 at 10 43 57" src="https://user-images.githubusercontent.com/537751/82419269-d3ec5f00-9a86-11ea-9e2b-be8950b3b29f.png">
ion

**Comment by vdrover** [comment]
Please try to not exclude php, log, config and logs files.

**Comment by ovidiul** [comment]
php, config and html files are now included

<img width="1210" alt="Screenshot 2020-05-20 at 17 17 04" src="https://user-images.githubusercontent.com/537751/82457154-c6060080-9abd-11ea-8327-f5d502d2aafe.png">

**Comment by vdrover** [comment]
I tested this with Akeeba backup. As you can see, the `backup` folder was not backed up. The goal here is to add the `backup` folder to the archive and any php|htm|html|config|htaccess files (skip everything else, including akeeba backup archives.  
 
<img width="854" alt="Image 2020-05-27 at 3 18 45 PM" src="https://user-images.githubusercontent.com/3143313/83068269-b7739800-a02d-11ea-860f-7ecf05a20f30.png">

**Comment by ovidiul** [comment]
I've posted a fix, here is the updated default regex rule

```
(wp-content\/updraft|wp-content\/uploads\/wp_all_backup|wp-content\/ai1wm-backups|wp-content\/plugins\/akeebabackupwp\/app\/backups)(.*)\.(.*)$(?<!config|php|html)
(.*)\.(svn|git)(.*)$
wp-content\/cache(.*)$
(.*)error_log$
```

<img width="609" alt="Screenshot 2020-05-28 at 06 44 39" src="https://user-images.githubusercontent.com/537751/83096589-b9317000-a0ae-11ea-9cf2-94e73fc3931c.png">

**Comment by vdrover** [comment]
I see the folder being included in the archive now. Just need `.htacess` and .htm` files.

**Comment by ovidiul** [comment]
.htaccess and .htm added as well now

<img width="687" alt="Screenshot 2020-05-28 at 17 03 53" src="https://user-images.githubusercontent.com/537751/83151513-53240780-a105-11ea-9152-566c69439c46.png">

**Comment by vdrover** [comment]
Working perfectly. Thanks!
