### ISSUE TITLE
Ajax error when viewing empty storage area

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#79]
I get this error when viewing the `Manage Backups` page and switching to SFTP and/or dropbox:

`DataTables warning: table id=manage_backups - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

I'm also seeing this on v4.1.4.

**Comment by ovidiul** [comment]
Error message should be fixed now, the issue that appears here is when the remote storage connection gets invalidated. For now, we will display an empty list of files with no error message.

**Comment by vdrover** [comment]
Fix confirmed.
