### ISSUE TITLE
Add `Local Storage` to the `Remote Storage` area?

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#81]
This is kind of a discussion and perhaps enhancement request. It relates to the location of the `Cleanup Options` for local and remote storage. 

If we rename `Remote Storage` to `Storage Locations` (or similar), we could add `Local Storage` as a tab along with the remote storage options. This new `Local` tab could allow someone to specify a new location (above root perhaps) and also include the local cleanup options. 

This way, the cleanup options could be removed from the current location (Settings) where they may be confused with Cleanup options for the remote locations.

@ovidiul thoughts?

**Comment by ovidiul** [comment]
Yes, this makes sense and will also help simplify the Settings area as well, feel free to put it in a new milestone.

**Comment by vdrover** [comment]
ignore.

**Comment by ovidiul** [comment]
New 'Local Storage' tab added and "Remote Storage" renamed to "Storage Locations", code is in milestone 4.2.9

I've also moved there the Backup Start Path and Backup Store Path options as it makes more sense

<img width="1058" alt="Screenshot 2020-06-23 at 11 55 08" src="https://user-images.githubusercontent.com/537751/85383308-7a28fa00-b548-11ea-9de8-c1d211f80353.png">

**Comment by vdrover** [comment]
wonderful.
