### ISSUE TITLE
Improve restore buttons

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#83]
I find the restore process a little hard to figure out. One way to improve this might be to remove the `skip/next` button entirely from the `file restore` screen. If someone wants to skip the file restore, they can do so by selecting `Only Database Backup`. 

I think the progress indicator can then move below the `Restore` button, which I would rename `Restore Files` to that we are super clear.

Once the progress indicator reaches 100%, we should then see a `Continue` button to proceed to the DB restore.

<img width="1108" alt="Image 2020-05-22 at 11 22 13 AM" src="https://user-images.githubusercontent.com/3143313/82689204-bd2d4000-9c1f-11ea-8b6e-28d6fefd80d3.png">

**Comment by vdrover** [comment]
I've been thinking more about this. The arrows on the buttons often don't jive with the text. Wireframes to follow.

**Comment by Ars92** [comment]
This should be considered while working for #258

**Comment by vdrover** [comment]
Complete.
