### ISSUE TITLE
Encrypt database password during restore

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#84]
This will improve security if the site has an intruder. Display `************` instead.

<img width="1113" alt="Image 2020-05-22 at 11 35 47 AM" src="https://user-images.githubusercontent.com/3143313/82689702-86a3f500-9c20-11ea-9566-a6d1ae41ef5e.png">

**Comment by ovidiul** [comment]
Password is now encrypted with type password

<img width="861" alt="Screenshot 2020-05-25 at 13 37 17" src="https://user-images.githubusercontent.com/537751/82805621-fae2d080-9e8c-11ea-960b-547406da4329.png">

**Comment by vdrover** [comment]
Fix Confirmed.
