### ISSUE TITLE
Rename `Cleanup by Date(days)`

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#85]
This language string is a bit confusing for me (thought the tooltip is very clear). Would `Cleanup by age` be more clear?

**Comment by ovidiul** [comment]
Yes, that makes sense. I've also adjusted the Remote Storage "Cleanup Days" to "Cleanup by Age" to be more clear.
<img width="653" alt="Screenshot 2020-05-25 at 17 44 41" src="https://user-images.githubusercontent.com/537751/82823070-8d946700-9eaf-11ea-890a-2d4edfb23f11.png">
![Uploading Screenshot 2020-05-25 at 17.44.52.png…]()

**Comment by vdrover** [comment]
Mind adding a space? `Cleanup by Age (days)`?

**Comment by ovidiul** [comment]
Sure, added now
<img width="540" alt="Screenshot 2020-05-25 at 19 41 33" src="https://user-images.githubusercontent.com/537751/82830957-c2101f00-9ebf-11ea-9cf8-179f09850445.png">

**Comment by vdrover** [comment]
Confirmed.
