### ISSUE TITLE
Add WP-CLI

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#90]
Per discussion in #60 .

**Comment by ovidiul** [comment]
WP CLI support has been added, the command name "xcloner_generate_backup" like

`wp-cli xcloner_generate_backup  --profile=<profile_name_OR_ID>`

and

`wp-cli xcloner_generate_backup  --help`

<img width="1238" alt="Screenshot 2020-06-23 at 14 04 02" src="https://user-images.githubusercontent.com/537751/85396428-68505280-b55a-11ea-95ec-7a48cd5b9077.png">
