### ISSUE TITLE
JS Error during restoration

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#91]
I received this error again, but this time during remote restore:
<img width="922" alt="Image 2020-05-27 at 4 04 25 PM" src="https://user-images.githubusercontent.com/3143313/83072175-ef7dd980-a033-11ea-8eed-ed96208e8893.png">

Clearing the browser cache did not help. The developer console showed one error:
<img width="1264" alt="Image 2020-05-27 at 4 06 18 PM" src="https://user-images.githubusercontent.com/3143313/83072237-04f30380-a034-11ea-8d58-90a324952163.png">

**Comment by ovidiul** [comment]
The missing favicon error is not related to XCloner and the restore process, can you detail if you had any other issues with that process?

**Comment by vdrover** [comment]
As you can see in the pic, I can’t select the type of restore...

**Comment by ovidiul** [comment]
Got it, it's fixed now, the issue relates to the materializecss framework upgrade i've done

**Comment by vdrover** [comment]
fix confirmed.
