### ISSUE TITLE
Scheduled backups does not respect the "Schedule recurrence"

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#99]
Hey @ovidiul 

Is it an expected behaviour When you set "Schedule recurrence" in site backend, to be ignored if you run the scheduled backups using a cronjob set on the server?

As you see on the printscreen below the backup runs 4 time per hour if I have a cronjob on server set to run every 15 mins:

*/15 * * * * php -q /public/20/wp-cron.php -p 2

Shouldn't the cronjob respect the setting selected in site backend in Schedule profile?

![Screen Shot 2020-06-05 at 9 48 08 PM](https://user-images.githubusercontent.com/3626762/83913646-66c01580-a778-11ea-9980-46b477324fd0.png)

![Screen Shot 2020-06-05 at 9 44 57 PM](https://user-images.githubusercontent.com/3626762/83913654-69226f80-a778-11ea-8f05-a3fcff2195e3.png)

**Comment by ovidiul** [comment]
I am unable to duplicate this issue, can you make sure you test this against a clean wordpress install with no other plugins and also make sure the

```define('DISABLE_WP_CRON', true);```

is present in the wp-config.php file

Let me know if you still get the issue afterwards.

**Comment by jimiero** [comment]
@ovidiul i was using server cronjobs, which was set to run every 15 mins, are you saying that scheduled backups don't require cronjobs?

**Comment by ovidiul** [comment]
To properly use the server cronjob, ideally you should disable the internal wp cron as explained here https://kinsta.com/knowledgebase/disable-wp-cron/ , did you already do that and still have the issue? The scheduled backup profile and recurrence still need to be set if you want them to run that way

Please note, do run the xcloner standalone cron, that is separate from the wordpress cron, and you need to access directly the wp-content/plugins/xcloner-backup-and-restore/xcloner.php file from the CLI command to trigger it

**Comment by vdrover** [comment]
@jimiero let's try with the cron formats as shown in the kinsta link above. Eg:
`wget -q -O - https://domain.com/wp-cron.php?doing_wp_cron >/dev/null 2>&1`

**Comment by jimiero** [comment]
@vdrover i've discussed with @ovidiul and he made a fix for this in the next milestone

**Comment by vdrover** [comment]
@jimiero why is this re-opened?

**Comment by jimiero** [comment]
Closing, this seems to be working now.

**Comment by onpaws** [comment]
Thank you, [this](https://github.com/watchfulli/XCloner-Wordpress/issues/99#issuecomment-641178269) was a helpful comment.
